### ISSUE TITLE
APK is too large , 50MB (debug) 46MB (release)

### ISSUE THREAD

**Issue by jhay06** [eclipsesource/tabris-js#2214] opened 2022-04-26 02:08 UTC
Hi ,
   upon checking and building tabris app , i noticed that the APK is too large when building , 

and i checked the files that was packed on that APK and found out that there are bunch of files on the android  unused resources folder, i think that is the default android resources 

![image](https://user-images.githubusercontent.com/5191437/165205011-a80bf7e1-630c-4fd3-a92b-720ca751eca9.png)

How can i exclude resources files that are not needed ? 

In kivy (python) , those built in android resources are removed automatically ? how can i achieve this on tabris ?

Thanks

**Comment by cookieguru** [comment] 2022-04-26 03:50
Duplicate of #2050
The XML files are only a few KB, and since they are plain text they zip quite small--I bet all of them take up 1-2kb in the resulting APK.  The majority of the space is used because both the x86 and arm runtimes are contained in the same package.  Note that building as a bundle (AAR) is not yet supported in the cloud build--you'll need to [build locally](https://docs.tabris.com/latest/build.html#local-build)

**Comment by jhay06** [comment] 2022-04-27 04:13
> Duplicate of #2050 The XML files are only a few KB, and since they are plain text they zip quite small--I bet all of them take up 1-2kb in the resulting APK. The majority of the space is used because both the x86 and arm runtimes are contained in the same package. Note that building as a bundle (AAR) is not yet supported in the cloud build--you'll need to [build locally](https://docs.tabris.com/latest/build.html#local-build)

hi , got this , is there any way that i can use R8 instead of Proguard ? or i can override the default build.gradle of cordova ? thanks

**Comment by elshadsm** [comment] 2022-05-16 13:58
@jhay06, I suggest building **Android App Bundle** (.aab) introduced in Tabris.js 3.3.0 version (see the [Support for Android App Bundles](https://tabris.com/tabris-js-3-3-released/) section). The feature is supported by the online build service as well. You can simply enable the `App Bundle` option on the online build settings page.

**Comment by mpost** [comment] 2022-06-21 09:17
Using the app bundle is recommended indeed. Please make use of it. Closing as resolved.

**Closed by mpost** 2022-06-21 09:17 UTC
Labels: question
