### ISSUE TITLE
Playing Icecast Stream - Android Headaches

### ISSUE THREAD

**Issue by acefxlabs** [eclipsesource/tabris-js#1638] opened 2018-04-26 13:21 UTC
Hello Everyone, thanks in advance for responses to this issue. 
I created an online radio using icecast and built a tabris app to play the radio. 
I used cordova media plugin to load the radio.

On iOS its almost instantly the audio plays and everything works super fine, but on Android it takes around 12 to 15 seconds before play.  Sometimes it doesnt even play at all. 
Then sometimes it plays songs that have already passed, 
I used the Media.release() option to free memory yet nothing

Has anyone exprienced this before, please i need help

Again, thanks in advance

**Comment by cookieguru** [comment] 2018-04-26 17:16
I have used the same plugin to play an Icecast stream as well on Android devices and didn't notice the lag you are seeing.

The plugin is fairly chatty, so try running [logcat](https://developer.android.com/studio/command-line/logcat) when you launch your app and you may be able to glean some info from there.  If you have installed the Android SDK you already have it; otherwise you can install the SDK or the lighter-weight [SDK Platform Tools](https://developer.android.com/studio/releases/platform-tools).

If the issue is related to the plugin and not Tabris.js you would need to contact the developer(s) of that plugin to resolve it.

**Comment by mpost** [comment] 2018-06-14 09:03
Closing this for now.

**Closed by mpost** 2018-06-14 09:03 UTC
