### ISSUE TITLE
Layout with percentage ignored egative offset 

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1655] opened 2018-05-30 15:02 UTC
So far this I tested this only on android, but there the following:
```js
widget.left = ['33%', -10];
```` 
does the same as
```js
widget.left = ['33%', 0];
```` 

Our documentation does not explicitly state that negative numbers don't work in this combination, so I would expect them to.

**Comment by mpost** [comment] 2018-05-30 15:03
This is a known issue of the used layout system on Android. Closing as duplicate of https://github.com/eclipsesource/tabris-js/issues/1406.

**Closed by mpost** 2018-05-30 15:03 UTC
Labels: android, bug
