### ISSUE TITLE
Introduce a "clipToBounds" property/API

### ISSUE THREAD

**Issue by jordiboehmelopez** [eclipsesource/tabris-js#307] opened 2015-03-02 11:20 UTC
This should be a Boolean value that determines whether subviews are confined to the bounds of the view.

**Comment by mpost** [comment] 2015-03-02 11:24
I think this is a duplicate of https://github.com/eclipsesource/tabris-js/issues/143

**Comment by mpost** [comment] 2015-11-05 14:40
Closing as duplicate of #143.

**Closed by mpost** 2015-11-05 14:40 UTC
Labels: feature
