### ISSUE TITLE
2.x app crashes on reload (via developer console)

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#1775] opened 2019-01-11 10:42 UTC
### Problem description

When clicking the reload button in the developer console of my 2.6.2 app it crashes while restarting.
My project consist of around 50 `.js` files. We do not yet use a bundler.
The app is served by `tabris serve` from the developer machine.

In that case we have to kill the app, restart it, and then reload from the development machine via the developer console. This always works after a fresh start of the app.

That developer experience is slow and cumbersome.

We started to kill the app immediately to reload it from the development server. As this means that we have to start the app twice, it is still very inconvenient.

Samsung Galaxy Tab S3 (Android 8.0.0) crashes on every reload reproducible.
Samsung Galaxy Note 10.1 (Android 5.1.1) only crashes sometimes on reload.

### Expected behavior

App does not crash when restarted via the reload button in the developer console.

### Environment

- Tabris.js version: 2.x-nightly
- Device: Samsung Galaxy Tab S3 and Samsung Galaxy Note 10.1
- OS: Android 8.0.0 and 5.1.1

**Comment by ahmadov** [comment] 2019-01-11 10:48
ADB Log:
```
01-10 14:53:34.530  1385  1385 D ViewRootImpl@4e86d3[TabrisActivity]: setView = DecorView@8b5e210[TabrisActivity] TM=true MM=false
01-10 14:53:34.574  1385  1385 D ViewRootImpl@4e86d3[TabrisActivity]: dispatchAttachedToWindow
01-10 14:53:34.601  1654  9973 V WindowManager: Relayout Window{23e97a u0 com.thieme.ecp.mobile.edp/com.eclipsesource.tabris.android.TabrisActivity}: viewVisibility=0 req=2048x1488 WM.LayoutParams{(0,0)(fillxfill) sim=#110 ty=1 fl=#81810100 pfl=0x20000 wanim=0x10302fd vsysui=0x600 sysuil=true needsMenuKey=2 colorMode=0 naviIconColor=0}
01-10 14:53:34.616   724   724 I SurfaceFlinger: id=2394 createSurf (2048x1536),1 flag=404, com.thieme.ecp.mobile.edp/com.eclipsesource.tabris.android.TabrisActivity#0
01-10 14:53:34.625  1385  1385 D ViewRootImpl@4e86d3[TabrisActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][2048,1536] result=0x7 surface={valid=true 3299864576} changed=true
01-10 14:53:34.845  1385  1385 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.thieme.ecp.mobile.edp/com.eclipsesource.tabris.android.TabrisActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@4e14a9a is not valid; is your activity running?
01-10 14:53:34.846  1385  1385 E AndroidRuntime: 	at com.eclipsesource.tabris.android.TabrisActivity.onDestroy(TabrisActivity.java:208)
01-10 14:53:34.860  1654  4560 W ActivityManager:   Force finishing activity com.thieme.ecp.mobile.edp/com.eclipsesource.tabris.android.TabrisActivity
01-10 14:53:35.368  1654  1704 W ActivityManager: Activity pause timeout for ActivityRecord{d2730c u0 com.thieme.ecp.mobile.edp/com.eclipsesource.tabris.android.TabrisActivity t211 f}
01-10 14:53:51.840  1654  1704 W ActivityManager: Activity destroy timeout for ActivityRecord{d2730c u0 com.thieme.ecp.mobile.edp/com.eclipsesource.tabris.android.TabrisActivity t211 f}
01-10 14:53:51.843  1654  1704 I WindowManager: Destroying surface Surface(name=com.thieme.ecp.mobile.edp/com.eclipsesource.tabris.android.TabrisActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2501 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:985 com.android.server.wm.WindowState.removeImmediately:2404 com.android.server.wm.WindowState.removeIfPossible:2612 com.android.server.wm.WindowState.removeIfPossible:2442 com.android.server.wm.WindowToken.removeAllWindowsIfPossible:143 com.android.server.wm.AppWindowToken.removeIfPossible:606 com.android.server.wm.AppWindowToken.onRemovedFromDisplay:674 
```

**Comment by mpost** [comment] 2019-01-14 08:33
Thanks for reporting. Since there is no snippet attached to reproduce the problem could it be related to any type of dialog or actionsheet that you are trying to show?

**Comment by josiahking** [comment] 2019-01-29 15:15
I think this might have to do with the javascript code and not the developer app. It has happened to me, but after restarting the app, i noticed that there is an error on my code that makes the app crash.
Although reloading app can be a pain with v2.x. Thanks to v3.x

**Comment by mpost** [comment] 2020-04-29 14:22
Please retest with 3.x closing this for now.

**Closed by mpost** 2020-04-29 14:22 UTC
Labels: 2.x, android, bug
