### ISSUE TITLE
TextInput questions

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1892] opened 2019-06-09 13:28 UTC
### Problem description
Even if the text visually has enough space to fit into the `TextInput` it is made scrolling
[![first example](https://i.gyazo.com/37a96e98c7f97b0c4730d989c56e6b16.gif)](https://gyazo.com/37a96e98c7f97b0c4730d989c56e6b16)

![second example](https://user-images.githubusercontent.com/26363214/59159278-4499a600-8ad8-11e9-83c3-6d16a1632ff9.gif)

Doesn't matter if it will has very small size or not
[![Image from Gyazo](https://i.gyazo.com/36b4d8d57b60384ea04c1a5e7331410b.gif)](https://gyazo.com/36b4d8d57b60384ea04c1a5e7331410b)

### Expected behavior
I would like to at least get an explanation of why this is happening at all if is not a bug. In other case just fix it guys 😄

### Environment
- Tabris.js version: 3.0.1
- Devices: NoxPlayer (Android 7.1.2 - EN lang) / Xiaomi Redmi 5 Plus (Android 8.1 - RU lang)

### Code snippet
[colors](https://pastebin.com/XW4PGCgh) and [i18n](https://pastebin.com/dFT3u3iQ) modules (idk why but maybe it's can be useful)

```typescript
    // Header
    new Composite({ top: 'prev() 0', left: 0, right: 0 }).append(
        // Search box
        new Composite({ left: 35, right: 'next() 35', cornerRadius: 20 }).append(
            // Search input
            // I specifically have red background to highlight the TextInput area for you
         new TextInput({ style: 'none', height: 40, font: '16px', textColor: colors.gray, cursorColor: colors.gray, left: 20, right: 'next() 15', floatMessage: false, message: i18n.feedSearchMessage }),
            new ImageView({ right: 20, centerY: 0, height: 15, image: { src: 'https://i.imgur.com/g3VF87L.png' } })
        ),
        // "More" button
        new Composite({ centerY: 0, width: 60, height: 40, right: 35, cornerRadius: 18, background: colors.blue })
    )
```

**Comment by fax1ty** [comment] 2019-06-09 15:00
Also, how to hide this cancel button? Any API?
![image](https://user-images.githubusercontent.com/26363214/59160593-8f231e80-8ae8-11e9-957e-2000df708902.png)

**Comment by mpost** [comment] 2019-06-11 08:20
Thanks for reporting the issue we can confirm the unexpected scrollability when setting a custom `height`. As a quick workaround you should not set the height on the `TextInput` itself but its parent to specify the height of your search field. Issue will be fixed though.

Regarding your second question with the clear button, this is shown when in `search` type. We will make this more flexible in the future to show/hide it on other types as well.

**Comment by mpost** [comment] 2019-06-11 08:35
After looking into the issue we found that it works as intended. When setting the height to be smaller than the intrinsic size, the text does not fit into the area of the inner offset anymore so the content starts to scroll. Otherwise it will be cut off. When you change your text font to be small enough to fit into the available space it will not scroll.

```js
import {contentView, TextInput} from 'tabris';

new TextInput({
  left: 16, right: 16, height: 40,
  background: 'red',
  font: '5px',
  text: 'Hello World'
}).appendTo(contentView);

```

**Comment by mpost** [comment] 2019-06-14 08:44
We have addressed an issue that should help you as well. The `padding` property is now ('nightly'  build) correctly applied inside the `TextInput`. This will allow you to overwrite the default `padding` and make the `TextInput` smaller than the default without it starting to scroll.

**Comment by fax1ty** [comment] 2019-07-26 19:34
Hi guys! New question. Is there any way to change the color of `floatMessage`?

**Comment by fax1ty** [comment] 2019-07-26 19:51
Also, the `font` value does not affect on `message` size

![image](https://user-images.githubusercontent.com/26363214/61977727-5095e480-b000-11e9-8bb8-28d016c780f3.png)

```js
contentView.append(
    new TextInput({ font: 'bold 12px', top: 'prev() 25', left: 25, right: 25, message: 'style: none, font: bold 12px', style: 'none', textColor: colors.red }),
    new TextInput({ font: '24px', top: 'prev() 25', left: 25, right: 25, message: 'style: none, font: 24px', style: 'none', textColor: colors.red }),
    new TextInput({ font: '12px', top: 'prev() 25', left: 25, right: 25, message: 'font: 12px', textColor: colors.red }),
    new TextInput({ font: '64px', top: 'prev() 25', left: 25, right: 25, message: 'font: 64px', textColor: colors.red }),
);
```

**Comment by mpost** [comment] 2019-08-01 08:24
Currently it is not possible to change the color/font of the message. The topic is discussed at https://github.com/eclipsesource/tabris-js/issues/875.

**Closed by mpost** 2019-08-01 08:24 UTC
