### ISSUE TITLE
ActivityIndicator does not render in some cases

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1003] opened 2016-10-10 04:15 UTC
![screenshot_2016-10-09-21-06-36 1](https://cloud.githubusercontent.com/assets/1888809/19226778/d3a36f8e-8e64-11e6-9602-2db17c663430.png)

Left: Andoid 6.0.1
Right: Android 4.4.2
Both: Tabris.js developer app 1.9.0 running on stock TouchWiz

``` js
var page = new tabris.Page({
    topLevel: true
}).open();

new tabris.ActivityIndicator({
  centerX: 0,
  centerY: 0
}).appendTo(page);
```

Confirmed with another user running on Android >= 5.0 (not TouchWiz) that the indicator does appear so like #844 this may be specific to TouchWiz.

**Comment by mpost** [comment] 2016-10-10 09:31
We couldn't reproduce the problem on a Galaxy S6. Could you provide some more details on the model?

**Comment by cookieguru** [comment] 2016-10-10 15:22
@mpost It's a Galaxy S5

**Comment by cookieguru** [comment] 2017-01-17 07:55
@mpost I tested this with a Nexus 5 running 6.0.1 that also does not display the `ActivityIndicator`.  I set the `background` property to red and on the 4.4.2 device I saw a red square with the activity indicator in the center of the screen.  On the Nexus 5 and the S5 both display nothing--even with the background set to red.

**Comment by mpost** [comment] 2017-01-17 12:12
@cookieguru Thanks for bringing the issue up again. Is it possible to replicate your described behavior on an emulator with a certain configuration?

**Comment by cookieguru** [comment] 2017-04-18 19:14
@mpost Testing both the Tabris.js and Tabris.js 2 developer apps from the Play Store yielded identical results using the fetch example.
- On  the S5, if I set the animator duration scale to 1x, the `ActivityIndicator` appears.  When it is off, it does not.
- On the Nexus 5, setting the animator duration scale to either 1x or off has no effect and the `ActivityIndicator` does not appear at all.
- I haven't found an emulator config that can reproduce the error, though I had only tried the 1.x client and with the duration set to 1x.  I can't get any emulator config to start right now.

**Comment by mpost** [comment] 2017-04-19 12:20
I have Tried the following snippet in the *Tabris.js 2* app on a Nexus 5:

```js
new tabris.ActivityIndicator({centerX: 0,centerY: 0})
  .appendTo(tabris.ui.contentView);
```

Which yields the following result:

![device-2017-04-19-142016](https://cloud.githubusercontent.com/assets/73655/25179719/58726ba6-250b-11e7-8517-d922b050e111.png)

**Comment by mpost** [comment] 2017-06-14 13:38
Closing this issue for now. Please reopen of the problem can still be reproduced with the snippet above.

**Closed by mpost** 2017-06-14 13:38 UTC

**Comment by cookieguru** [comment] 2017-06-14 20:10
After a little more testing, I have concluded that the *Animator duration scale* is to blame.  This one can be marked as WontFix
