### ISSUE TITLE
Add the ability to control gravity of TextView

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#2013] opened 2020-03-16 10:34 UTC
Currently, it is not possible to control the vertical position of the text inside `TextView`. As far as I know, Android has this property called `gravity`. It would be quite useful to have this property in Tabris

**Comment by cookieguru** [comment] 2020-03-16 16:50
Duplicate of #1887

**Comment by mpost** [comment] 2020-03-23 11:03
Rightfully pointed out to be a duplicated. iOS currently does not support it which stops us from implementing it cross platform. An Android only option would be possible.

**Closed by mpost** 2020-03-23 11:03 UTC
