### ISSUE TITLE
Make it possible to use the drawer on the right side

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1758] opened 2018-11-05 11:14 UTC
Drawer is a very useful thing. No need to create custom widgets. The slider menu is already built into Tabris, but there is one problem. Sometimes it is necessary to open the drawer from the right side to the left, but this is not possible at the moment

It would be great if the drawer had the "side" property with the choice of the opening side

**Comment by cookieguru** [comment] 2018-11-05 16:46
Duplicate of #628

**Comment by mpost** [comment] 2018-11-07 14:40
Closing as duplicate of #628

**Closed by mpost** 2018-11-07 14:40 UTC
