### ISSUE TITLE
Selector API: Support complex selectors

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#504] opened 2015-06-30 09:51 UTC
Currently, our selector API only supports single selector expressions (`*`, `#id`, and `type`). Once we have class selectors (#360), we should also support combined selectors such as `TextView.foo`, `TextView#foo`, or `TextView.foo.bar`.

Later, we may want to add support for pseudo classes, e.g. `TextView:first-child`, attributes `TextView[enabled=false]` and even child selectors `Tab > TextView`.

It may be worthwhile to look at existing libraries for parsing selector expressions such as [sizzle.js](https://github.com/jquery/sizzle/blob/master/src/sizzle.js).

**Comment by mpost** [comment] 2018-06-15 13:58
Closing as duplicate of https://github.com/eclipsesource/tabris-js/issues/1678

**Closed by mpost** 2018-06-15 13:58 UTC
Labels: feature
