### ISSUE TITLE
Subviews are not clipped by parent bounds when elevation set

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1275] opened 2017-05-05 12:32 UTC
As seen in navigationview-properties.js: Scrolling the controls up shows them outside of the bonds of its ScrollView parent, overlapping the pages and toolbar from the NavView (reproduced on iPhone)

**Comment by karolszafranski** [comment] 2017-05-10 14:46
Duplicate of: https://github.com/eclipsesource/tabris-js/issues/1064

**Comment by mpost** [comment] 2017-06-08 08:46
After some discussion we agreed that the issue related to #1064 technically but the user might not get the idea. We therefore reopen the issue.

**Comment by mpost** [comment] 2017-06-08 08:46
The same problem as described above can also be seen in the websocket chate example where messages are shown over the TextInput when multiple messages are shown.

**Comment by karolszafranski** [comment] 2017-06-14 09:15
Currently as a workaround I suggest to put a second empty composite under your scroll view (or other scrollable area), and drop shadow from this view, instead of setting the elevation on the scroll view.

**Comment by maoamid** [comment] 2017-06-15 10:15
Another situation, maybe it help
Image cannot exceed parent size

### Code snippet

```javascript
const { Composite, ImageView, ui } = require('tabris');

let cardCompositeWithElevation = new Composite({
    left: 6, top: 0,
    height: 160, width: 160,
    background: '#ff6600',
    elevation: 4,
    cornerRadius: 2
}).appendTo(ui.contentView);

new ImageView({
    left: 0, top: 0,
    image: { src: 'http://via.placeholder.com/300x100' }
}).appendTo(cardCompositeWithElevation);

let cardCompositeWithoutElevation = new Composite({
    left: 6, top: 'prev() 10',
    height: 160, width: 160,
    background: '#9933ff',
    cornerRadius: 2
}).appendTo(ui.contentView);

new ImageView({
    centerY: 0,
    image: { src: 'http://via.placeholder.com/300x100' }
}).appendTo(cardCompositeWithoutElevation);

```

**Comment by karolszafranski** [comment] 2017-06-16 11:18
@maoamid you are right, this issue affects generally subviews being drawn out of bounds of parents with `elevation` set to any value greater than 0. Most often we see this in scrollable areas, thats where the issue title comes from.

Fix for the issue has to be delayed, so anyone who has this issue this is a workaround:

```js
const { Composite, ImageView, ScrollView, ui } = require('tabris');

let elevationOnlyview = new Composite({
    left: 6, top: 0,
    height: 160, width: 160,
    elevation: 10,
    cornerRadius: 8
}).appendTo(ui.contentView);

let cardWithoutElevation = new ScrollView({
    left: 6, top: 0,
    height: 160, width: 160,
    background: '#9933ff',
    cornerRadius: 8,
}).appendTo(ui.contentView);

new ImageView({
    left: 0, bottom: 0,
    image: { src: 'http://via.placeholder.com/100x300' }
}).appendTo(cardWithoutElevation);
```

**Closed** 2017-08-23 14:11 UTC
Labels: bug, ios
