### ISSUE TITLE
Patches can break developer app

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#553] opened 2015-07-22 12:18 UTC
If you test the installPatch feature with the Developer App using the URL tab, patches will be applied to every other snippet loaded from the same URL.

**Comment by wilsonna** [comment] 2015-08-03 08:31
Noted on the different URL. I've actually appended a timestamp to my URL to eliminate the possibility of caching issues. Clearing the Developer App data would be a bit drastic for me as I've lots of test data in the localStorage of the Developer App that I would like to retain.

Perhaps the Developer app can work a bit differently from the standalone app by clearing all patches each time our app is reloaded. I think that would be the expected behaviour since it would more often than not be the latest version during development stage and we would only ever use the patch feature when we are testing it. But I also understand that this would mean that doing a tabris.ui.reload() may actually clear the patches before we actually get to test its effects.

Alternatively, there could be a new option in the Developer app to allow to manually clear all patches for a given app.

Yet another alternative, and maybe this is even considered a feature, allow patches to be revoked. In other words, new files added in a patch can be deleted by a subsequent patch. Right now, I think we can only add or update.

**Comment by mpost** [comment] 2015-08-03 10:09
I would prefer the last suggestion by @wilsonna to provide API to remove the patch. Thereby the developer has full control of what to do. We have discussed to improve the patch feature and that is one way to move it forward.

**Comment by mpost** [comment] 2018-06-15 13:11
Closing this issue sine we will remove the patch feature.

**Closed by mpost** 2018-06-15 13:11 UTC
Labels: bug
