### ISSUE TITLE
Close App

### ISSUE THREAD

**Issue by sergio-doman** [eclipsesource/tabris-js#663] opened 2015-10-20 20:33 UTC
As I see, there is no way to close app, something like App.exit() or App.close().
Is it possible to implement? Thank you

**Comment by cookieguru** [comment] 2015-10-20 20:46
See https://github.com/eclipsesource/tabris-js/issues/610#issuecomment-136643671

**Comment by mpost** [comment] 2015-10-21 08:13
@sergio-doman Explicitly closing an app is rather uncommon. Could you provide a use case where such a feature would make sense?

**Comment by sergio-doman** [comment] 2015-10-21 18:23
Sure, let's imagine I have simple e-book app with 20-30 pages and I'm looking for the way how to close it  after exit confirmation dialog

**Comment by mpost** [comment] 2015-10-22 08:13
Navigating back past the last top level page should close the app (given there seems to be a bug as described in #610).

**Comment by mpost** [comment] 2015-12-11 13:39
Since explicitly closing is very uncommon we will close this issue for now. Please reopen if you think otherwise.

**Comment by wilsonna** [comment] 2016-10-09 11:08
I would like to re-open this case as I think that we should allow the app to be closed in the case of Logout.  The natural expectation for a user when they tap the logout button would be to perform the necessary housekeeping (terminate session etc.) and then exit the app.

**Comment by mpost** [comment] 2016-10-10 08:46
While i still think that a normal standalone app will not require this feature, an app that only executes an utility task can benefit from this feature.

Eg, You are an calendar app that is opened from another app to add an event and than to close itself.

**Comment by ralfstx** [comment] 2017-09-07 15:23
Closing as a duplicate of #610.

**Closed by ralfstx** 2017-09-07 15:23 UTC
Labels: feature
