### ISSUE TITLE
Caret position is different on iOS and Android when text is set on TextInput

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#995] opened 2016-10-04 14:42 UTC
Execute the snippet:
```
var textInput = new tabris.TextInput({
  centerX: 0, top: 50, width: 320,
  font: "24px"
}).appendTo(page);

textInput.on('input', function(widget, text) {
  var texts = {rap: "Remote Application Platform"}
  let lastSpaceIndex = text.lastIndexOf(' ');
  let lastWord = text.substring(lastSpaceIndex + 1);
  if (texts[lastWord]) {
    let replacedText = text.substring(0, lastSpaceIndex + 1) + texts[lastWord];
    widget.set('text', replacedText);
  }
});
```
when you type "rap" the text in the text field will be replaced with "Remote Application Platform". On iOS the caret position is at the end and you can continue typing. On Android is at 0. We have to decide, which platform behaves correctly and to align the other.

**Comment by cookieguru** [comment] 2016-10-05 06:43
Duplicate of #537

**Comment by ralfstx** [comment] 2016-10-05 07:23
Thanks @cookieguru

**Closed by ralfstx** 2016-10-05 07:23 UTC
Labels: bug
