### ISSUE TITLE
Widget.animate() reverse does not always work on iOS

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#238] opened 2015-01-21 12:07 UTC
Example:
label.animate({transform: {scaleX: 2, scaleY: 2, rotation: Math.PI * 0.75}}, {duration: 1000,  reverse: true});

If you add the property repeat: 1 to the animation options it works fine. This should not be necessary, as repeat defaults to 1.

**Comment by jordiboehmelopez** [comment] 2015-02-02 12:47
Why should repeat default to 1.
Currently it default to 0.

**Comment by jordiboehmelopez** [comment] 2015-02-02 12:54
Here are some examples we (iOS & Android) figured out and implemented as test cases:

Repeat:0 andReverse:NO:
// 1:|->| animation

Repeat:0 andReverse:YES:
// 1:|->| animation

Repeat:1 andReverse:NO:
// 1:|->| animation
// 2:|->| repetition 1

Repeat:1 andReverse:YES:
// 1:|->| animation
// 2:|<-| repetition 1

Repeat:2 andReverse:YES:
// 1:|->| animation
// 2:|<-| repetition 1
// 3:|->| repetition 2

Repeat:3 andReverse:YES:
// 1:|->| animation
// 2:|<-| repetition 1
// 3:|->| repetition 2
// 4:|<-| repetition 3

**Comment by jordiboehmelopez** [comment] 2015-02-02 12:56
So, considering the specified behavior, what exactly does not always work?

**Comment by ralfstx** [comment] 2015-02-02 13:40
The documentation says it defaults to `1`, maybe that's just a typo. JS passes this parameter to the clients unchanged. @mpost what is the default for `repeat` on Android?

**Comment by mpost** [comment] 2015-02-02 13:44
@ralfstx Not sure what the default would be. by default it is 0. No repeat. The scheme jordi posted above is correct.

**Comment by ralfstx** [comment] 2015-02-02 13:50
@jordiboehmelopez @mpost Thanks. I'll fix it in the docs.

**Comment by mpost** [comment] 2015-12-11 14:28
Closing as "fixed/works as intended".

**Closed by mpost** 2015-12-11 14:28 UTC
Labels: bug
