### ISSUE TITLE
Allow to set focus on TextInput programmatically

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#259] opened 2015-02-04 15:02 UTC
Setting focus should allow the user to type in a particular text field.

**Comment by ralfstx** [comment] 2015-02-26 17:29
We didn't manage to address this in 0.9.2. I think that, even though an important feature, it is not release-critical because it's new API that can as well be added after 1.0.

**Comment by wilsonna** [comment] 2015-07-13 15:08
+1 for this

**Comment by gosia-eclipsesource** [comment] 2015-08-05 12:27
Closing this as I believe it's a duplicate of #136.

**Closed by gosia-eclipsesource** 2015-08-05 12:27 UTC
Labels: enhancement
