### ISSUE TITLE
ScrollView can not work in android 5.0.2

### ISSUE THREAD

**Issue by whitekyo** [eclipsesource/tabris-js#1755] opened 2018-10-19 15:33 UTC
I used the demo code: the ScrollView still can not work in android 5.0.2

const {Button, ScrollView, TextView, ui} = require('tabris');

// Create a horizontal scroll view and populate it with text views

let scrollView = new ScrollView({
  left: 0, right: 0, top: '40%', bottom: '40%',
  direction: 'horizontal',
  background: '#234'
}).appendTo(ui.contentView);

for (let i = 0; i <= 50; i++) {
  new TextView({
    left: i * 30 + 20, centerY: 0, width: 30,
    textColor: 'white',
    text: i + '°'
  }).appendTo(scrollView);
}

new Button({
  left: 16, bottom: 16,
  text: 'scroll'
}).on('select', () => scrollView.scrollToX(310))
  .appendTo(ui.contentView);

**Comment by cookieguru** [comment] 2018-10-19 17:32
I tested your snippet and it works fine:

![screenshot_20181019-102851](https://user-images.githubusercontent.com/1888809/47234300-3ac90400-d38a-11e8-8f0d-7a327f4c874d.png)

**Comment by whitekyo** [comment] 2018-10-24 15:17
what is the version of your device?

**Comment by mpost** [comment] 2018-10-29 10:10
Also what tabris version are you using there was a known bug in earlier android version that prohibited the scroll to.

**Comment by mpost** [comment] 2019-01-24 14:26
Closing this as "can't reproduce". Please reopen if you still have the issue.

**Closed by mpost** 2019-01-24 14:26 UTC
