### ISSUE TITLE
Change navigation menu background

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#292] opened 2015-02-21 02:31 UTC
Is there any way to change navigation menu background color? Change style from pages slide menu and navigation will give us power on customization.

**Comment by ralfstx** [comment] 2015-02-22 20:01
It's not yet documented, but you can use `tabris.ui.set("background", color)`.

**Comment by mpost** [comment] 2015-02-23 08:52
The slide in navigation menu is no affected by the tabris ui background color. On android you can choose between a light and dark color scheme but you can not apply any styling programmatically. I'd rather think this is a duplicate of https://github.com/eclipsesource/tabris-js/issues/203

**Comment by ralfstx** [comment] 2015-03-06 20:21
Sorry, I misunderstood the question.

Yes, the background will be customizable as part of #203.

**Closed by ralfstx** 2015-03-06 20:21 UTC
