### ISSUE TITLE
Downscaled image blurry when set with delay

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1599] opened 2018-03-11 17:05 UTC
### Problem description

When the `image` property of an `ImageView` has been set after the widget creation (with delay), the image is rendered blurry if it had to be downscaled in order to fit the view.

### Expected behavior

Setting `image` on creation and after the widget has been created should lead to the same results.

### Environment

- Tabris.js version: 2.4
- Device: iPad Pro
- OS: 11.2.6

### Code snippet

Replace the `imageview.js` snippet with:
```javascript
const {ImageView, ui} = require('tabris');

let image = new ImageView({
  width: 100, height: 100,
  centerX: 0, centerY: 0,
  // image: 'resources/target_200.png'
}).appendTo(ui.contentView);

setTimeout(() => {
  image.image = 'resources/target_200.png';
}, 1000);
```

**Comment by karolszafranski** [comment] 2018-05-03 15:34
When the image is set in original `imageview.js` snippet, size of the `ImageView` is not know. That is because views were not laid out yet. In this case, image cache implies that `'resources/target_200.png'` means:
```js
{
    src: 'resources/target_200.png',
    width: 200, // original image width
    height: 200, // original image height
    scale: 1.0 // default scale equals 1.0
}
```

With your changes, when the image is set after a delay, size of the image view is already known - it was laid out and its dimensions are `{100, 100}`. Image cache imply that image should have the same size, but while `scale` is not set, again default 1.0 is used.
```js
{
    src: 'resources/target_200.png',
    width: 100, // width of the image view
    height: 100, // height of the image view
    scale: 1.0 // default scale equals 1.0
}
```

That's where the difference in size comes from.

**Comment by mpost** [comment] 2018-06-12 09:35
@cpetrov Your assumption is correct. On Android the image is cached in its original size so that it can be served in the app in the appropriate size. What kind of platform alignment did you have in mind?

**Comment by karolszafranski** [comment] 2018-06-25 09:11
@mpost I guess @cpetrov wanted to have same cache behavior on both platforms. iOS caches the resized version of the image. I'm surprised that Android doesn't because iOS implementation was rewritten a few months ago and we would not take the additional effort of managing the resized images if that would not be required. Didn't you change it lately? On iOS it worked like this since the beginning.

**Comment by mpost** [comment] 2018-06-25 12:48
@karolszafranski The android client has never cached the resized image on disc; only in memory. Thereby the image can be recreated for changing sizes.

**Comment by patrykmol** [comment] 2019-09-02 07:24
I cannot reproduce it anymore. Most likely fixed with https://github.com/eclipsesource/tabris-ios/commit/72cdb5a91bfe8e59e194bb1c130c14ce182a1b51.

**Closed** 2019-09-02 07:24 UTC
Labels: bug, ios
