### ISSUE TITLE
CollectionView undefine propert get

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#980] opened 2016-09-19 09:29 UTC
view.get("lastVisibleIndex")
Says undefined

TypeError: Cannot read property 'get' of

**Comment by cpetrov** [comment] 2016-09-19 12:15
Hi @iteearmah, can you post a code snippet where this problem is reproducible?

**Comment by iteearmah** [comment] 2016-09-19 14:12
```
 newsList.on("scroll", function(view, scroll) {
          if (scroll.deltaY > 0) {
            totalItemsChk=0;
            var totalItems=parseInt(view.get("items").length);
            var remaining = totalItems - parseInt(view.get("lastVisibleIndex"));
            
            if (remaining ==1) 
            {
              console.log('remaining:'+remaining+' | items count'+view.get("items").length+' | lastVisibleIndex: '+view.get("lastVisibleIndex"));
              loadNewItems(newsList,json_url,'news_list');
            }

          }
  });
```

**Comment by iteearmah** [comment] 2016-09-19 14:13
the view.get("lastVisibleIndex") works now but loads the function loadNewItems multiple times

**Comment by iteearmah** [comment] 2016-09-19 16:20
Other huddle, how can I prevent CollectiveView list  to load on only specific TabFolder

**Comment by cookieguru** [comment] 2016-09-19 20:01
> the `view.get("lastVisibleIndex")` works now but loads the function loadNewItems multiple times

From [the docs](https://tabrisjs.com/documentation/latest/api/CollectionView#scroll-widget-event): The `scroll` event is
> Fired while the collection view is scrolling.

When the first pixel of your last cell is visible, your if condition becomes true.  As the user continues to scroll, the event continues to be fired and your condition is still true as more of the last cell becomes visible.


It looks like you're trying to implement infinite scrolling.  Take a look at the [Reddit example](https://github.com/eclipsesource/tabris-js/blob/v1.9.0/examples/reddit/reddit.js#L95) which does just that.  It uses a global boolean to determine whether or not the application is currently fetching new items which prevents that call from executing multiple times while the user is scrolling.

Finally, the `parseInt()` calls are not necessary; both of the places you're using them are already integers.

**Comment by cookieguru** [comment] 2016-09-19 20:01
> Other huddle, how can I prevent CollectiveView list to load on only specific TabFolder

Can you provide an example?

**Comment by natanraj** [comment] 2016-09-27 14:16
@iteearmah I avoided duplicate loading by setting a flag = true in initialize block and inside change:item, i reset thsi to false. I added the items only when it is true

**Comment by mpost** [comment] 2016-11-11 13:15
Closing this for now. @iteearmah Feel free to open another issue if you still have an issue.

**Closed by mpost** 2016-11-11 13:15 UTC
