### ISSUE TITLE
Snippet/example missing to show different keyboard types for text input

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#258] opened 2015-02-02 15:02 UTC
We should have a snippet or example that shows how to use the different keyboard types that can be associated with a text widget.

Especially email and URL types are important on mobile.

The current documentation https://tabrisjs.com/documentation/widget-types#text does not mention this types on the text widget at all.

**Comment by mpost** [comment] 2015-02-10 16:30
Duplicate of https://github.com/eclipsesource/tabris-js/issues/232

**Comment by ralfstx** [comment] 2015-02-10 16:38
Right, documentation should be part of #232.

**Closed by ralfstx** 2015-02-10 16:38 UTC
Labels: enhancement
