### ISSUE TITLE
Question : topLevel attribute alternative

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1177] opened 2017-03-09 06:49 UTC
hi, From tabris2.x onwards, i guess topLevel is removed. Any idea what is the alternate for this?

My usecase is : how can I dispose of all my underneath pages once an order is confirmed and I need to come back to Home page (which is my topLevel) and eventually i can prevent user go back using navigation button on the header bar ... Would autoDispose : false on each of these previous pages suffice ?

**Comment by cookieguru** [comment] 2017-03-09 07:25
With Tabris.js 2.0, pages are appended to a `NavigationView` which you append to `tabris.ui`.  For more information see [here](https://tabrisjs.com/documentation/2.0/ui#using-pages).

Your use case sounds similar to #1124.  To dismiss all pages, you can simply call `dispose()` on the page right before your "Home" page.  One way of preventing the user from navigating back would be to [hide the toolbar](https://tabrisjs.com/documentation/2.0/api/NavigationView#toolbarvisible) and [prevent back navigation](https://tabrisjs.com/documentation/latest/api/app#backnavigation-app-event).

**Comment by ralfstx** [comment] 2017-03-09 09:31
Right, that's the same request as #1124. We'll look into this again after the Beta 2 release. Stay tuned.

The `autoDispose` property serves a different purpose. It prevents pages from being disposed on user back navigation and so allows to re-use those pages later on. This property should be used with care as it can easily cause memory leaks.

Closing as duplicate of #1124.

**Closed by ralfstx** 2017-03-09 09:31 UTC

**Comment by natanraj** [comment] 2017-03-10 12:16
@ralfstx @cookieguru  I personally felt, the one powerful attribute of tabris.js was topLevel. Badly missing it though the solution of using existingpage.dispose() on each new page addition is somewhat not elegant...

**Comment by cookieguru** [comment] 2017-03-10 20:10
@natanraj The 1.x branch isn't going away any time soon; you don't _have_ to migrate to 2.0 if you don't want to.

Manually disposing pages in order to switch to another one is not required.  They dispose of themselves when closed (unless the aformentioned `autoDispose` property is set to true).

In 1.x, everything had to be added to a `Page`.  In 2.x, you can append directly to `tabris.ui.contentView` or you can add elements to a `NavigationView`.  A `NavigationView` is just a stack of pages.  This gives you a lot more flexibility; you could, for instance, have multiple wizard flows each in their own `NavigationView` and switch between them.  In 1.x this was a lot harder to do.

Besides having `topLevel` pages automatically show up in a `PageSelector` what other functionality do you feel is missing?  It's true that [the `PageSelector` has been removed in 2.0](https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md#page-and-pageselector), but the functionality is straightforward to re-implement and you have much more flexibility on which pages go in to the selector.

**Comment by ralfstx** [comment] 2017-03-13 09:08
@natanraj Interesting. Can you explain what you liked about the `topLevel` attribute? I personally found it hard to understand and to explain its implications, and it was also badly named - as these pages were actually not at the *top level* but at the root of the page stack.

The new model is much simpler. There is just a single page stack you can append pages to and remove pages from, and there are no different types of pages.

If you have a use case that was easier to implement with the old API, let's discuss it.
