### ISSUE TITLE
iOS Build Server issue

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#718] opened 2016-01-04 16:37 UTC
iOS Build Server issue - I'm getting a lot of different errors when building an iOS right now, it was just working earlier today

**Comment by bFlood** [comment] 2016-01-04 18:43
any one having issues building for iOS on the tabris build servers?

**Comment by irbull** [comment] 2016-01-04 18:44
I just tried it and I'm seeing an error as well (looks like mine is related to signing keys). Is that similar to what you are seeing?

**Comment by bFlood** [comment] 2016-01-04 18:48
no, the errors were related to different plugins. right now, its stopping at tabris maps (same errors as here: https://github.com/eclipsesource/tabris-js/issues/703 )

I compiled successfully this morning and nothing has changed since then, so I'm assuming something changed on the build server

cheers

**Comment by irbull** [comment] 2016-01-05 07:23
Nothing has changed on our end, but we do use travisci for the actual build job. I don't see any incidents reported, but they may have updated something today. I'll check with @patrykmol tomorrow and see if he has any ideas. Sorry about this.

**Comment by jonek** [comment] 2016-01-05 09:49
@bFlood: I just triggered a new build of the latest version of tabris-maps-example in our build service. The build was successful and the app executes fine on an iOS device.

**Comment by jonek** [comment] 2016-01-05 10:42
The warning is expected as we already bumped the version in Tabris.js for the next release.

**Comment by bFlood** [comment] 2016-01-05 13:50
no problem, thanks for looking into it. as of this morning, it is still failing. full build log here:
https://gist.github.com/bFlood/666e4599ac15e4f1458a

**Comment by jonek** [comment] 2016-01-05 14:03
Two ideas:
1. Try to rule out that the problem is related to other plugins you are using. In the Tabris-maps-example we only use the tabris-maps plugin.
2. From the error messages I suspect the problem is related to the Swift hooks that need to be executed. Maybe this is caused by the config.xml in the wrong location (and thus the hooks not beeing executed correctly)? See #703: spaces in project name and config.xml in root folder.

**Comment by bFlood** [comment] 2016-01-05 14:11
thanks @jonek 

I agree, this is likely an issue with other plugins but I haven't made any changes there

1.  my tabris-maps-example compiles as well
2.  nothing had changed in my project, I was able to compile yesterday morning. When I went back an hour later, the errors started up. that makes me think the Swift hooks are setup correctly but maybe not being called for some reason (is the whole hooks workflow stable?) if you read the bottom of https://github.com/eclipsesource/tabris-js/issues/703 you'll notice I had the same issue back then, nothing changed and the build mysteriously started working (at that time, I had just assumed you had changed something in the background)

**Comment by jonek** [comment] 2016-01-05 14:46
1. Does your fork build now against tabris.js nightly?
2. We did not commit any changes to tabris.js or tabris-maps since yesterday. So if the build of your app for iOS using the tabris-maps plugin fails now it would assume a change in some of the TravisCI components. @pmol will be able to help with any iOS build issues earliest next Monday.

We are really interested to find out the underlying problem here because it seems it is caused by something that is not under our direct control.

**Comment by jonek** [comment] 2016-01-05 14:56
It is always possible that code in a third party Cordova plugin was changed between builds. Do you consume those plugins directly from a git repository or via a pinned version number from npm?

**Comment by bFlood** [comment] 2016-01-05 19:09
agreed, looking into this. I did notice this when comparing the log of build that worked versus all the others that failed: (notice the missing ``` -import-objc-header /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/ESMaps-Bridging-Header.h``` ). I have no idea what would control this in your build service but I'm also not sure how another plugin would affect it.

this build worked:
``` log
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    cd /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/travis/.rvm/rubies/ruby-2.0.0-p643/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name SDLMobile -O -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -target arm64-apple-ios7.1 -g -Xfrontend -serialize-debugging-options -I /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device -F /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device -F /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/CordovaLib/Tabris -F SDLMobile/Plugins/com.googlemaps.ios -c -j1 /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/ESMap.swift /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/ESMarker.swift -output-file-map /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/Objects-normal/arm64/SDLMobile-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/Objects-normal/arm64/SDLMobile.swiftmodule -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/SDLMobile-generated-files.hmap -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/SDLMobile-own-target-headers.hmap -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/SDLMobile-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/SDLMobile-project-headers.hmap -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device/include -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device/usr/local/lib/include -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/UninstalledProducts/include -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/UninstalledProducts/iphoneos/include -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/DerivedSources/arm64 -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/Objects-normal/arm64/SDLMobile-Swift.h -import-objc-header /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/ESMaps-Bridging-Header.h -Xcc -working-directory/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios
CompileSwift normal arm64 /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/ESMap.swift
```


this build failed:
``` log
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    cd /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/travis/.rvm/rubies/ruby-2.0.0-p643/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name SDLMobile -O -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -target arm64-apple-ios7.1 -g -Xfrontend -serialize-debugging-options -I /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device -F /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device -F /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/CordovaLib/Tabris -c -j1 /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/ESMap.swift /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/ESMarker.swift -output-file-map /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/Objects-normal/arm64/SDLMobile-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/Objects-normal/arm64/SDLMobile.swiftmodule -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/SDLMobile-generated-files.hmap -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/SDLMobile-own-target-headers.hmap -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/SDLMobile-all-target-headers.hmap -Xcc -iquote -Xcc /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/SDLMobile-project-headers.hmap -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device/include -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device/usr/local/lib/include -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/UninstalledProducts/include -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/UninstalledProducts/iphoneos/include -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/DerivedSources/arm64 -Xcc -I/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/SDLMobile.build/Release-iphoneos/SDLMobile.build/Objects-normal/arm64/SDLMobile-Swift.h -Xcc -working-directory/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios
CompileSwift normal arm64 /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/ESMap.swift
```

**Comment by bFlood** [comment] 2016-01-06 16:56
@jonek plugins - half are pinned but all of the others have not changed within the timeframe of getting successful builds for ios. 

our tabris maps fork did compile successfully on a our simple maps example app

so, its obviously something to do with extra plugins but the timing and lack of change (e.g. worked, then didn't work an hour later with zero changes) still make me think something changed on the build servers

thanks

**Comment by irbull** [comment] 2016-01-06 17:10
Nothing has changed 'explicitly' on the build server. I've been trying to
hunt down things that may have accidentally changed (for example,
provisioning a new version of Cordova during the build). I've not found
anything yet, but I think your finding that '-import-objc-header' is
missing, may be relevant. We'll keep you updated as soon as we have more
information.

Thanks for your patience.
Ian

On Wed, Jan 6, 2016 at 8:56 AM, Brian Flood <notifications@github.com>
wrote:

> @jonek <https://github.com/jonek> plugins - half are pinned but all of
> the others have not changed within the timeframe of getting successful
> builds for ios.
>
> our tabris maps fork did compile successfully on a our simple maps example
> app
>
> so, its obviously something to do with extra plugins but the timing and
> lack of change (e.g. worked, then didn't work an hour later with zero
> changes) still make me think something changed on the build servers
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/tabris-js/issues/718#issuecomment-169387286>
> .
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by bFlood** [comment] 2016-01-06 17:11
thanks @irbull let me know if you need any other info or a test run

**Comment by bFlood** [comment] 2016-01-11 14:40
can someone look at this today? thanks

**Comment by patrykmol** [comment] 2016-01-12 08:16
@bFlood Sorry for late response. I am looking into this right now.

**Comment by bFlood** [comment] 2016-01-12 13:36
thanks @patrykmol let me know if you want me to test anything (or need my full logs)

**Comment by patrykmol** [comment] 2016-01-18 19:31
Closing for now.

**Closed by patrykmol** 2016-01-18 19:31 UTC

**Comment by cookieguru** [comment] 2016-01-19 07:01
Experiencing another issue.  It's not even getting to the `grunt` step.  Travis isn't reporting any certificate errors but isn't progressing beyond that step.

http://pastie.org/pastes/10693903/text?key=f52olkhx6mrzlk2g9ibq

Ran two of these and same result.  Build was working earlier today--at least I think; I uploaded the wrong certificate.

**Comment by cpetrov** [comment] 2016-01-23 10:02
@cookieguru http://pastie.org seems to be down, can you send us the log in another way?

**Comment by cookieguru** [comment] 2016-01-23 10:09
@cpetrov [Here's](http://pastebin.com/raw/2UmCXdXk) the build from before and [here's](http://pastebin.com/raw/RFqqQKZj) another that I just kicked off.  The build was successfully reached the key signing stage the second time but I now have to work out the issues with my keys.

**Comment by cpetrov** [comment] 2016-01-23 10:31
@cookieguru Thank you for your input! We can reproduce the problem with logs being cut off on one of our builds. I have opened eclipsesource/tabris-js#740 to track progress on this issue.
