### ISSUE TITLE
Setting items to Picker causes trigger of an unexpected select event

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1367] opened 2017-06-01 11:11 UTC
### Problem description

- Actual Behavior: An unexpected select event is triggered when items are set to Picker. 
- Expected Behavior: Setting items to Picker must not cause any select event. 

### Environment

- Device (name and OS version): Nexus 6P, Android 7.1.2
- Tabris.js version: 2.0.0-rc1-dev.20170425

### Code snippet

```
import {Picker, ui} from 'tabris';

const AIRPORTS = [
  {
    id: 'SFO',
    name: 'San Francisco'
  },
  {
    id: 'TXL',
    name: 'Berlin Tegel'
  },
  {
    id: 'FRA',
    name: 'Frankfurt'
  }
];

let picker = new Picker({
  class: 'picker',
  left: 0, right: 0, centerY: 0
}).appendTo(ui.contentView);

picker.on('select', () => {
  console.log('selected event is triggered');
});

picker.set({
  items: AIRPORTS,
  itemText: function (item) {
    return item.name;
  }
});
```

When running the snippet without any selection, 'selected event is triggered' is printed in the console.

**Comment by ralfstx** [comment] 2017-06-01 13:47
@elshadsm The `items` property has been replaced with `itemCount`. I can't reproduce the problem with the picker snippet and latest nightly. Can you?

**Comment by elshadsm** [comment] 2017-06-01 13:52
Sorry @ralfstx, one of our project tabris version is **2.0.0-rc1-dev.20170425**. So the project has not migrated to the latest tabris version yet.

**Comment by ralfstx** [comment] 2017-06-01 16:03
Ok, I'll close this issue then. Please reopen if you can reproduce it with nightly.

**Closed by ralfstx** 2017-06-01 16:03 UTC
Labels: Android, bug
