### ISSUE TITLE
Allow overlay on top of Action Bar in Android

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#520] opened 2015-07-07 15:06 UTC
I'm not sure if this is applicable to iOS, but right now, the drawer slides out under the Action Bar, contrary to the current design convention which slides over the Action Bar. In addition, I would like to place a translucent layer over my app to provide some textual help for first time users, but I'm not able to set this layer above the Action Bar.

As such, I had to resort to implementing my own Action Bar, and forgoing all the default features that come with it (e.g. Action, SearchAction, page title etc.)

**Comment by mpost** [comment] 2015-07-07 15:28
@wilsonna Being able to control the visibility of the app bar is high on our list. In an upcoming update we will allow you to show and hide the app bar so that you can use the space of the entire screen.

**Comment by wilsonna** [comment] 2015-07-07 15:32
Thanks Moritz :)

**Comment by jonek** [comment] 2015-07-22 13:52
Closing as a duplicate of #234.
@wilsonna Please reopen if this issue would not be solved by a mechanism to just hide the app bar.

**Comment by wilsonna** [comment] 2015-07-23 05:04
I'm not sure if I have the rights to re-open the issue. Can't seem to find the re-open button.

This would not be resolved by hiding the app bar as the intention of the overlay is to provide help over certain actions or buttons of the page, and the action bar may contain actions which I wish to focus on.

**Comment by mpost** [comment] 2015-07-23 07:50
@wilsonna You are right that the linked issue is not a duplicate of your idea to place content above the main toolbar (action bar).

**Comment by mpost** [comment] 2015-12-11 14:10
While i still see that the issue could be interesting we don't think it is high priority.

**Comment by mpost** [comment] 2016-11-11 14:38
With tabris 2.0 you will be able to place content above the new tabris.ui replacement called `NavigationBar`.

**Closed by mpost** 2016-11-11 14:38 UTC
Labels: priority: medium
