### ISSUE TITLE
Top-level Page not working after returning there from another page

### ISSUE THREAD

**Issue by DinHere** [eclipsesource/tabris-js#953] opened 2016-08-20 11:34 UTC
I currently ran into a promblem in my (under-construction) app. While the app is fully working when I first open My Scratchpad or when I hit reload from the dev console(this means that the next button  will get me to page2 and the result button will give the result I want as you can see in the first two screenshots), it is not working when I go back to Page1 by pressing the back button from page2.This means that when I press the next button it wont get me to page2 and the Dev console throws these errors(screenshot3).
I should note that I use page2.open() to open Page2, the back button is the default, page1 is top-level and page2 is not, and my device is n android one.
Any help would be really appreciated!
![14059960_162863407455089_1442523449_o](https://cloud.githubusercontent.com/assets/20650935/17830872/676dbab2-66e2-11e6-8cf7-4d8d81e61020.png)
![14075212_162863400788423_1900307702_o](https://cloud.githubusercontent.com/assets/20650935/17830873/6c54e60e-66e2-11e6-9e7e-6b53379037da.png)
![14045234_162863647455065_1534505925_o](https://cloud.githubusercontent.com/assets/20650935/17830874/71a4effa-66e2-11e6-9ed1-e5915cc8b9da.png)

**Comment by cpetrov** [comment] 2016-08-20 12:09
Hi @DinHere, I couldn't reproduce your issue with the following snippet:

```js
var page = new tabris.Page({title: "Page 1", topLevel: true}).open();

var button = new tabris.Button({
  centerX: 0, top: 100,
  text: "Open page 2"
}).appendTo(page);

new tabris.TextView({
  centerX: 0, centerY: 0,
  text: "Page 1's text",
  font: "24px"
}).appendTo(page);

button.on("select", function() {
  var page2 = new tabris.Page({title: "Page 2"}).open();
  new tabris.TextView({
    centerX: 0, centerY: 0,
    text: "Page 2's text",
    font: "24px"
  }).appendTo(page2);
});
```

Can you post a snippet of code, which demonstrates the problem?

**Comment by DinHere** [comment] 2016-08-20 12:24
Hello @cpetrov and thanks for your help. Here are 2 screenshots of my code. I noticed that you create the page2 when the button is hit while I create it at the very begining. Do you thins that this might cause my issue?

**Comment by cpetrov** [comment] 2016-08-20 12:51
Yes, closing a page [disposes it](https://tabrisjs.com/documentation/latest/widget-basics#disposing-of-a-widget), so it can't be reused. See [Documentation/The Page Stack](https://tabrisjs.com/documentation/latest/ui#the-page-stack). In this case you would want to create a new page.

Please reopen if this doesn't fix your issue.

**Closed by cpetrov** 2016-08-20 12:51 UTC

**Comment by DinHere** [comment] 2016-08-20 13:03
@cpetrov Promblem fixed!thank you :+1:
