### ISSUE TITLE
Webview to load HTML file in app

### ISSUE THREAD

**Issue by acefxlabs** [eclipsesource/tabris-js#1623] opened 2018-04-04 15:32 UTC
Is there a way i can use webView to load an HTML file that resides in the app.
I have tried calling via localhost and this does not work

Thanks

**Comment by mrmccormack** [comment] 2018-04-04 19:04
- I'm working on a tutorial that might answer part of your question...
- I think I'll add the feature to load an external HTML file, but this current solution allows you to add text placeholders to the HTML. I see lots of uses for WebViews and l love learning Tabris.js.

--

You can try it out on **Tabris.js playground.**
- Here is a GitHub Gist:
- https://gist.github.com/mrmccormack/4104654a8cd70c23eec86875549186b6

>Screenshot on iPhone 6
![unnamed](https://user-images.githubusercontent.com/3249215/38328383-ccce7c6c-3818-11e8-8bf0-fbafd1f29bf4.png)

**Comment by cookieguru** [comment] 2018-04-04 19:17
The app does not have a built-in webserver, so you can't just point the URL to a local resource.  As @mrmccormack pointed out, you can [directly set the HTML of the WebView](https://tabrisjs.com/documentation/latest/api/WebView#html).

You can use the [fs API](https://tabrisjs.com/documentation/latest/api/fs.html#readfilepath) to read the contents of a local file.

Alternatively, if the HTML is stored in a JS or JSON file, you can simply `require` it and set the `html` property to a variable exposed by that file, e.g. `webview.html = require('file.json').html;`

There's also [`getResourceLocation`](https://tabrisjs.com/documentation/latest/api/app.html#getresourcelocationpath) but I haven't tested it with WebViews and can't say for sure if it'll work.

Because there is no internal webserver, you can't directly link from `page1.html` to `page2.html` in your generated code.  Instead, you should listen to the [`navigate`](https://tabrisjs.com/documentation/latest/api/WebView#navigate) to intercept the loading of a page and use your custom loader.

**Comment by mrmccormack** [comment] 2018-04-04 19:25
cookieguru: I like your *"Alternatively..."* with a `json` file for the HTML etc. - I'm going to do a example of that, It will be a cleaner solution to my Gist posted.  Rob

**Comment by acefxlabs** [comment] 2018-04-26 13:55
@cookieguru @mrmccormack Thanks, was able to load it. 
The HTML audio in android refuses to play, no matter how much i try, even by passing action in JS

**Comment by cookieguru** [comment] 2018-05-03 04:01
@acefxlabs A `WebView` does not have access to the bundled assets (any of the files you add to a project).

**Comment by mpost** [comment] 2018-06-14 09:14
Closing this issue for now as "works as intended".

**Closed by mpost** 2018-06-14 09:14 UTC

**Comment by frederikbosch** [comment] 2020-02-21 16:32
> @acefxlabs A WebView does not have access to the bundled assets (any of the files you add to a project).

Is this still true? If I run this: `let resource = app.getResourceLocation('resources/test.html');` in my test app, a URL is returned: `http://my-ip:8080/resources/test.html`, which I can load in the webview, but I wonder what is being returned when the app is actually build. I was hoping it to return a local file, then I found this issue with that quote of yours.

**Comment by cookieguru** [comment] 2020-02-21 18:46
@frederikbosch That method works because all resources are loaded over http in develop mode.  You can use [this workaround](https://github.com/eclipsesource/tabris-js/blob/master/snippets/webview-webmessaging.js#L24) to load local resources
