### ISSUE TITLE
Tabris Plugin Firebase for Admob

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1086] opened 2017-01-03 17:22 UTC
Firebase for admob

**Comment by iteearmah** [comment] 2017-01-09 11:19
:-)

**Comment by cookieguru** [comment] 2017-01-09 19:06
There isn't enough information here to describe what the problem is.  If you're still having issues with these two plugins working together, please try my earlier suggestion on https://github.com/eclipsesource/tabris-js/issues/1083#issuecomment-270267836.

Since the [tabris-plugin-firebase](https://github.com/eclipsesource/tabris-plugin-firebase) and admob plugins each work on their own, compatibility with Tabris.js isn't an issue but rather it's an issue of compatibility with each other.

**Comment by mpost** [comment] 2017-01-10 08:55
@cookieguru That would be correct. Having the two different strains of libraries will cause problems.

**Comment by iteearmah** [comment] 2017-01-17 13:58
Hi, can you help with a sample app with the two implemented :-)

**Comment by mpost** [comment] 2017-01-17 16:29
@iteearmah help will be hard to give. you should rely on one version only.

**Comment by mpost** [comment] 2017-06-14 10:54
Closing this for now. Please target the https://github.com/eclipsesource/tabris-plugin-firebase for future issues.

**Closed by mpost** 2017-06-14 10:54 UTC
