### ISSUE TITLE
Intrinsic size sometimes not working as expected for percentage layouts

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#853] opened 2016-05-23 14:15 UTC
In this case the red composite's size is smaller than expected and text gets cut off on both Android and iOS. 

| iOS | Android |
| --- | --- |
| ![simulator screen shot 23 05 2016 16 09 21](https://cloud.githubusercontent.com/assets/2341769/15473544/cfa793be-2100-11e6-9dc0-96f458af08ac.png) | ![screenshot_20160523-160448](https://cloud.githubusercontent.com/assets/2341769/15473450/6d0244de-2100-11e6-83df-0f4d29e6c9fe.png) |

``` javascript
var page = new tabris.Page({
  title: "Hello, World!",
  topLevel: true
});

var container = new tabris.Composite({
  top: 0, left: 0, right: 0,
  background: "red"
}).appendTo(page);

var square = new tabris.Composite({
  top: "8%", centerX: 0, width: 100, height: 100,
  background: "purple"
}).appendTo(container);

new tabris.TextView({
  top: square, centerX: 0,
  text: "lorem ipsum dolor sit amet"
}).appendTo(container);

page.open();
```

**Comment by mpost** [comment] 2017-06-14 15:54
Works as intended by now. Closing as fixed.

**Closed by mpost** 2017-06-14 15:54 UTC
Labels: bug
