### ISSUE TITLE
Provide a way to handle content behind semi-transparent statusbar and NavigationBar

### ISSUE THREAD

**Issue by jordiboehmelopez** [eclipsesource/tabris-js#290] opened 2015-02-19 13:47 UTC
Here is an example image I found:
![images](https://cloud.githubusercontent.com/assets/61378/6267661/36d181aa-b846-11e4-99ce-b06bf18df49a.jpeg)

**Comment by mpost** [comment] 2015-02-19 13:49
I think this is a duplicate of https://github.com/eclipsesource/tabris-js/issues/171

**Comment by jordiboehmelopez** [comment] 2015-02-19 13:53
Maybe. The important part is, that the start coordinates 0,0 are not at top left of the screen, instead below the status bar. The content would only become visible under the status bar, when it is scrolled.

**Comment by ralfstx** [comment] 2015-03-02 10:49
Agree it's a dup. Copied relevant information to #171.

**Closed by ralfstx** 2015-03-02 10:49 UTC
