### ISSUE TITLE
Issue with dynamic height TextView Rendering

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1445] opened 2017-07-27 06:44 UTC
On android I am noticing a strange behavior with certain elements primarily related to a TextView with a "dynamic" height. This is reproducible with the following snippet. I have seen this strange behavior without the collection view, but this is the easiest way to reproduce. In both cases it was triggered by the TextView. So far I have only seen this issue on latest Android Pixel. 

```
var nav = new tabris.NavigationView({
    left: 0, top: 0, right: 0, bottom: 0,
    background: 'purple'
}).appendTo(tabris.ui.contentView)
var page = new tabris.Page();
var comp = new tabris.Composite({left: 0, right: 0, top: 0, background: 'red'});
new tabris.TextView({
        layoutData: {top: 10, left: 10, right: 10},
        textColor: 'white',
        text: 'hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello',
        maxLines: 10
    }
).appendTo(comp)
page.append(comp);


let content = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
var cv = new tabris.CollectionView({
    layoutData: {left: 0, top: 'prev()', right: 0, bottom: 0},
    background: "blue",
    itemCount: content.length,
    refreshEnabled: true,
    cellHeight: (index) => {
        return 64;
    },
    createCell: (cellType) => {
        let cell = new tabris.Composite();
        new tabris.Composite({
            layoutData: {bottom: 0, left: 0, right: 0, height: 1},
            background: 'gray'
        }).appendTo(cell);
        new tabris.TextView({
            class: "title",
            layoutData: {left: 64, top: 14, right: 35},
            maxLines: 1,
            font: '14px',
          text:'hello'
        }).appendTo(cell);
        return cell;
    }
})
cv.appendTo(page);
page.appendTo(nav)
```

== Before Scrolling ==

![before scrolling](https://user-images.githubusercontent.com/822784/28657480-3478ec5e-725c-11e7-8a4a-82c0deaae9ac.png)

== After Scrolling ==

![after scrolling](https://user-images.githubusercontent.com/822784/28657479-328106a2-725c-11e7-891a-dc799e6d62ad.png)

**Comment by mpost** [comment] 2017-07-27 09:37
Thanks for the report. We can confirm the issue. In fact to showcase the problem the snippet can be condensed to:

```js
let comp = new tabris.Composite({
  left: 0, right: 0, top: 0,
  background: 'red'
}).appendTo(tabris.ui.contentView);

new tabris.TextView({
  left: 16, right: 16,
  textColor: 'white',
  text: 'TextView',
}).appendTo(comp);

new tabris.CollectionView({
  left: 0, top: 'prev()', right: 0, bottom: 0,
  background: 'blue',
  itemCount: 20,
  cellHeight: 64,
  createCell: () => new tabris.TextView({background: 'green', text: 'CollectionView item'})
}).appendTo(tabris.ui.contentView);
```

Which results in:

![screenshot_1501148196](https://user-images.githubusercontent.com/73655/28664214-e53df882-72bf-11e7-945e-f47094102212.png)

The problem can only been when the console is pinned though. in that scenario certain screen sizes likely come into play. the problem can also not be observed when the composite or textview are not left _and_ right attached.

**Comment by avianey** [comment] 2017-09-04 12:04
@mpost your snippet shows the problem without the pinned console on OnePlus ONE Android 6.0.1 API 23 ... only at first display then layout recomputing done through screen rotation is okay (same as with pinned console on Android 7 API 25)

**Comment by tbuschto** [comment] 2018-06-01 10:36
@mpost Any progress on this issue?

**Comment by cpetrov** [comment] 2018-06-01 12:05
@tbuschto It seems this issue has been fixed in Tabris.js 2.5. I cannot reproduce the issues from the snippets anymore. Please reopen if this issue still persists for your use case.

**Closed by cpetrov** 2018-06-01 12:05 UTC
Labels: android, bug
