### ISSUE TITLE
How can I add atob to my Tabris 2.x App in such a way, that I can be consumed by plugins? (iOS)

### ISSUE THREAD

**Issue by samynomad** [eclipsesource/tabris-js#2210] opened 2022-02-16 10:40 UTC
## Question

I am using the Plugin [cordova-plugin-bluetoothle](https://www.npmjs.com/package/cordova-plugin-bluetoothle) in my Tabris 2.x App.
Whenever I call one of the functions of the plugin that use `atob` I get an error: `ReferenceError: Can't find variable: atob`

## Environment

* I use Tabris 2.x nightly and I have set up my project to use TypeScript.
* The Plugin used is https://www.npmjs.com/package/cordova-plugin-bluetoothle
* I only run the app on iOS - I have not tested this on Android

## Example

In my config.xml I have: 
```
<plugin name="cordova-plugin-bluetoothle" spec="6.6.1" />
```

The code I call:
```
    const bytes = bluetoothle.encodedStringToBytes('U3Vic2NyaWJlIEhlbGxvIFdvcmxk');
    const value = bluetoothle.bytesToString(bytes);
    console.log(value);
```

The Error I get: 

```
Promise {
  <rejected> ReferenceError: Can't find variable: atob
  encodedStringToBytes@file:///private/var/containers/Bundle/Application/E23ADD74-861F-4B9B-96B4-72172A97B0B2/diwo%20Vorkommnisse.app/www/plugins/cordova-plugin-bluetoothle/www/bluetoothle.js:191:20
  BleTestComp@http://192.168.6.52:8080/dist/BleTestComp.js:26:55
  http://192.168.6.52:8080/dist/App.js:29:46
  generatorResume@[native code]
  http://192.168.6.52:8080/dist/App.js:8:75
  tryCallTwo@http://192.168.6.52:8080/node_modules/tabris/tabris.min.js:1:1530
  doResolve@http://192.168.6.52:8080/node_modules/tabris/tabris.min.js:1:3488
  Promise@http://192.168.6.52:8080/node_modules/tabris/tabris.min.js:1:1927
  http://192.168.6.52:8080/dist/App.js:4:36
  http://192.168.6.52:8080/dist/index.js:11:37
  get@http://192.168.6.52:8080/node_modules/tabris/boot.min.js:1:842
  value@http://192.168.6.52:8080/node_modules/tabris/boot.min.js:1:1099
  n@http://192.168.6.52:8080/node_modules/tabris/boot.min.js:1:3505
  file:///private/var/containers/Bundle/Application/E23ADD74-861F-4B9B-96B4-72172A97B0B2/diwo%20Vorkommnisse.app/www/cordova.js:713:16
  file:///private/var/containers/Bundle/Application/E23ADD74-861F-4B9B-96B4-72172A97B0B2/diwo%20Vorkommnisse.app/www/cordova.js:133:43
  file:///private/var/containers/Bundle/Application/E23ADD74-861F-4B9B-96B4-72172A97B0B2/diwo%20Vorkommnisse.app/www/cordova.js:1428:34
  http://192.168.6.52:8080/node_modules/tabris/boot.min.js:1:3629 }
```

**Comment by cookieguru** [comment] 2022-02-16 10:51
See https://github.com/eclipsesource/tabris-js/issues/899#issuecomment-229715395

**Comment by tbuschto** [comment] 2022-02-16 10:58
duplicate of https://github.com/eclipsesource/tabris-js/issues/899#issuecomment-229715395

**Closed by tbuschto** 2022-02-16 10:58 UTC
Labels: question
