### ISSUE TITLE
fetch arrayBuffer Android

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1332] opened 2017-05-17 20:18 UTC
Tried to fetch a local file into an Array Buffer.
First try with `XHR`. iOS: ok - Android: faild.
Second try with `fetch`. Same result again.
This is my script error or tabris.js error?

**Textscript**
```javascript
var filename = tabris.app.getResourceLocation('src/img/framework7.png');
console.log(filename);

fetch(filename).then(function(response) {
    return response.arrayBuffer();
  }).catch(function(err) {
	console.error(err);
  }).then(function(buffer) {
	console.log(typeof buffer);
	console.log(buffer);
});
```

**Output (iOS, Android)**
![bildschirmfoto 2017-05-17 um 22 16 49](https://cloud.githubusercontent.com/assets/28459193/26174123/9d4ede9a-3b4e-11e7-90a3-42a452adbac8.png)

**Comment by capotti** [comment] 2017-05-18 06:14
with a http-ressource this works fine - on Android also.
Maybe fetch is not intended to grep a local file !?

Method 3: use cordova-plugin-file
Has anyone used the cordova-plugin-file - an can give me an example?
The only example I found seems to be outdated https://github.com/eclipsesource/tabris-js-file-open-example/blob/master/www/app.js

I'd love just an example wich demonstates:

- how to read static ressources from www-Folder into an ArrayBuffer / String
- how to write persistent/temporary file from ArrayBuffer / String

**Comment by cookieguru** [comment] 2017-05-18 06:29
I think @bflood has done at least the second one.

**Comment by capotti** [comment] 2017-05-18 06:42
@cookieguru thank's!

**Comment by mpost** [comment] 2017-05-18 09:18
@capotti Thanks for the feedback. It should be possible to fetch() local files on android. We will investigate the issue.

**Comment by capotti** [comment] 2017-05-18 14:24
@mpost you only get my trouble - but behind: tabris.js really rocks!

**Comment by mpost** [comment] 2017-05-18 15:37
@capotti The issue is fixed in the upcoming nightly.

**Comment by ishigo1987** [comment] 2017-05-18 17:05
guys you make a great work thank you very much for tabrisJs

**Comment by bFlood** [comment] 2017-05-18 17:07
@cookieguru no, I have not tried to load a file that way. I was able to get a PNG from tabris Canvas using getImageData-> ImageData

**Comment by capotti** [comment] 2017-05-18 19:56
@bFlood Thanks for response nevertheless!

**Comment by capotti** [comment] 2017-05-19 12:18
fetch in tabris nightly does not fire a promise any more at all?

**Testscript**
```javascript
var filename = tabris.app.getResourceLocation('src/img/my.txt');
console.log(filename);

fetch(filename).then(function(response) {
    return response.text();
  }).catch(function(err) {
	console.error('error: ' + err.message);
  }).then(function(buffer) {
	console.log(typeof buffer);
	console.log(buffer);
});
```

**Output ^2.0.0-rc1**
![bildschirmfoto 2017-05-19 um 14 18 28](https://cloud.githubusercontent.com/assets/28459193/26247410/1054eda8-3c9e-11e7-8dd0-e187419a25d9.png)


**Output nightly**
https://tabrisjs.com/downloads/nightly-2.x/tabris.tgz

![bildschirmfoto 2017-05-19 um 14 13 31](https://cloud.githubusercontent.com/assets/28459193/26247379/e81e4f50-3c9d-11e7-81a9-2aa51be2cce1.png)

**Comment by mpost** [comment] 2017-05-19 12:42
We have renamed several internal events. please make sure to use nightly tabris.js as well as nightly android client.

**Comment by capotti** [comment] 2017-05-19 12:53
What do you mean with "nightly tabris.js as well as nightly android client" ?
You mean tabris cli?
(I only use local build)

**Comment by mpost** [comment] 2017-05-19 13:45
you need to download the nightly tabris-android platform from the download page, as well as having nightly in your package.json.

**Comment by capotti** [comment] 2017-05-19 15:17
```
export TABRIS_IOS_PLATFORM=/Users/dirk/Library/tabris_ios_platform_nightly
export TABRIS_ANDROID_PLATFORM=/Users/dirk/Library/tabris_android_platform_night
```

works on Android with response.arrayBuffer() also (cool!!!)
but not on iOS (nightly)

![bildschirmfoto 2017-05-19 um 17 15 43](https://cloud.githubusercontent.com/assets/28459193/26254478/f81926b4-3cb6-11e7-8c13-6fa1a57cd26f.png)

**Comment by capotti** [comment] 2017-05-23 14:23
@mpost 

> you need to download the nightly tabris-android platform from the download page, as well as having nightly in your package.json.

Cannot find it any more...?

**Comment by cookieguru** [comment] 2017-05-23 19:16
@capotti They're still on [the download page](https://tabrisjs.com/download)

**Comment by capotti** [comment] 2017-05-23 19:19
cannot see the nightly platform download
![bildschirmfoto 2017-05-23 um 21 18 41](https://cloud.githubusercontent.com/assets/28459193/26372246/89eac0a4-3ffd-11e7-872a-8dab62437923.png)

**Comment by capotti** [comment] 2017-05-23 19:20
Aaaah I have to login. Sorry

**Comment by cookieguru** [comment] 2017-05-23 19:21
#1111

**Comment by karolszafranski** [comment] 2017-05-24 09:25
@capotti when you use valid path, on iOS 10 you will get:
```js
console.log(typeof buffer); // object
console.log(buffer); // {}
console.log(buffer instanceof ArrayBuffer); // true
```

**Comment by capotti** [comment] 2017-05-24 10:19
@karolszafranski Thanks for this tip!
With tonights nightly platform I tested successful to get
arrayBuffer, text, json.
Thank you! I will close this issue.

By the way:
I read about a common method: users always choose response.**text** and convert the result into required destination type. So they can handle malformed files better - e.g. malformed json.

**Closed** 2017-05-24 10:19 UTC
Labels: Android, bug
