### ISSUE TITLE
Maps Capabilities

### ISSUE THREAD

**Issue by builtap** [eclipsesource/tabris-js#370] opened 2015-03-30 03:26 UTC
Is it possible yet? Any examples? I would need to create routes as well. Thanks.

**Comment by jonek** [comment] 2015-03-30 11:03
Please have a look at the maps related Cordova plugins. If a Cordova plugin does not depend on WebView it should be possible to use it with Tabris.js. We have not tested any map related plugins ourselves yet. Please keep us posted.

**Comment by paulocarvalhodesign** [comment] 2015-03-31 17:54
I think that would be great to have a map widget, I have faith that will happen:)
As an alternative you can use the webView (https://tabrisjs.com/snippets/#web-view)
You can create a simple page on your server and pass params through webView to render a map google or other type.
As there is no mapView widget think that would be a good approach:)
In an app I am building Im using this approach, however it is a very simple map that only shows where you are marker and where you going marker with highlighted route.
Also seems to perform well as google apis are loaded on my webpage and not on the app.
Just a thought, looking forward for that mapView widget :)

**Comment by paulocarvalhodesign** [comment] 2015-03-31 18:08
Duplicate of #202 ?

**Comment by paulocarvalhodesign** [comment] 2015-03-31 19:38
https://github.com/leecrossley/cordova-plugin-directions
This may be of interest

**Comment by gosia-eclipsesource** [comment] 2015-12-09 10:27
Custom maps widget is completed for Android and iOS: https://github.com/eclipsesource/tabris-maps
The iOS version will be supported starting with Tabris.js 1.5.

**Closed by gosia-eclipsesource** 2015-12-09 10:27 UTC
