### ISSUE TITLE
Make non-selected tab image/text tint color configurable

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#882] opened 2016-06-07 13:27 UTC
Currently, TabFolder Tabs in selected state are tinted in the `textColor` of the TabFolder. However, there is no way to configure the tint color of the tabs which are not selected (text and image). The default tint color of non-selected items is a shade of gray on iOS, which may not look well on some darker backgrounds. On Android, opacity is reduced. One would prefer to manually tweak those settings and probably also be able to set icon and text color for both states independently from each other.

**iOS**
<img width="289" alt="bildschirmfoto 2016-06-07 um 15 19 24" src="https://cloud.githubusercontent.com/assets/2341769/15859032/948d0d30-2cc3-11e6-8b16-58fdbbe23eda.png">

**Android**
<img width="332" alt="bildschirmfoto 2016-06-07 um 16 32 37" src="https://cloud.githubusercontent.com/assets/2341769/15861705/7dafc6e8-2ccd-11e6-8bef-9fce50d31d28.png">

Example (tabfolder snippet taken as a starting point):

``` javascript
var page = new tabris.Page({
  title: "TabFolder",
  topLevel: true
});

var tabFolder = new tabris.TabFolder({
  textColor: "white",
  background: "gray",
  layoutData: {left: 0, top: 0, right: 0, bottom: 0},
  paging: true // enables swiping. To still be able to open the developer console in iOS, swipe from the bottom right.
}).appendTo(page);

var createTab = function(title, image, seletedImage) {
  var tab = new tabris.Tab({
    title: title, // converted to upper-case on Android
    image: {src: image, scale: 2},
    selectedImage: {src: seletedImage, scale: 2} // only used by iOS
  }).appendTo(tabFolder);
  new tabris.TextView({
    layoutData: {centerX: 0, centerY: 0},
    text: "Content of Tab " + title
  }).appendTo(tab);
};

createTab("Cart", "images/cart.png", "images/cart-filled.png");
createTab("Pay", "images/card.png", "images/card-filled.png");
createTab("Statistic", "images/chart.png", "images/chart-filled.png");

page.open();

tabFolder.on("change:selection", function(widget, tab) {
  console.log(tab.get("title"));
});
```

**Comment by mpost** [comment] 2018-06-15 12:50
Closing as duplicate of https://github.com/eclipsesource/tabris-js/issues/1676

**Closed by mpost** 2018-06-15 12:50 UTC
Labels: feature
