### ISSUE TITLE
Provide API to resize layout when keyboard opens

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1070] opened 2016-12-14 15:20 UTC
Often it is useful to resize the UI to fit the visible area when the keyboard opens. This makes it possible to e.g. always show a button below the selected text input when it gets focus (see example below).

This was the behavior of the Android client on Tabris.js 1.x. On 2.x, the layout is only modified when the developer drawer is opened.

On iOS, the UI is not resized when the keyboard opens. Input fields may be covered by the keyboard when it opens (reproducible in the example below).

It would be useful to unify the default behavior on both platforms and provide API to enable/disable it.

Example:

```js
tabris.ui.contentView.append(
  new tabris.ScrollView({left: 0, top: 0, right: 0, bottom: 0}).append(
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.TextInput({left: 0, top: 'prev() 10', right: 0}),
    new tabris.Button({left: 0, top: 'prev() 10', right: 0})
  )
);

tabris.ui.contentView.find('ScrollView').first().on('resize', function(scrollView) {
  let childrenHeight = 0;
  let children = tabris.ui.contentView.find('ScrollView').first().children();
  children.forEach(child => childrenHeight += child.bounds.height + 10);
  if (childrenHeight - scrollView.bounds.height > 0) {
    scrollView.scrollToY(childrenHeight - scrollView.bounds.height);
  }
});
```

**Comment by natanraj** [comment] 2017-02-06 12:13
I think i am facing this problem already. I have a text field on the lower part of the page (not inside a scrollview);  When I want to type in this field, the Keyboard aptly comes up, but it hides the TextField and eventually unable to see what I type. Any suggestions welcome.

**Comment by cookieguru** [comment] 2017-02-06 20:03
@natanraj That's basically the story of my life on Android--content not moving in to the viewport at all or doing so in a bizzairre way.

I'd say that the way you have it set up is the intended behavior.  If you set up a page and append several tall elements to it, the last few items will get cut off on lower-resolution devices (regardless of keyboard visibility).  The only way around this is to place a `ScrollView` on the page and append all items to that.

**Comment by mpost** [comment] 2017-02-07 10:15
To embed your content in a `ScrollView` is mostly the right choice anyways since you are can not rely on a certain screen size. The use could also activate split screen mode where your apps window would be really small.

**Comment by natanraj** [comment] 2017-02-07 10:37
Thanks @mpost  and @cookieguru

**Comment by natanraj** [comment] 2017-03-01 09:39
Slightly struggling yet. Does the order in which we add into the scrollview matter ?

**Comment by cookieguru** [comment] 2017-03-01 09:41
@natanraj Yes, you should add items to the `ScrollView` in the same order you'd add them to a `NavigationView`, `Page`, or `Composite`.

**Comment by natanraj** [comment] 2017-03-01 09:44
oh. the entire navigationView onwards inside the ScrollView ?

**Comment by natanraj** [comment] 2017-03-01 09:46
@cookieguru i had multiple page apps (each as separate JS). Not all pages have had this textField. So i was trying to add the scrollView approach in only the respective page's JS. Would that be an issue ?

**Comment by mpost** [comment] 2017-03-01 11:27
Note on the original issue.

With Tabris.js 2.x we always relayout the ui when the keyboard opens, giving you full control over the appearance of your screen.

**Comment by natanraj** [comment] 2017-03-01 12:47
@mpost May be i am not understanding. In multi-page scenario, will the approach of cpetrov works ? or am I misunderstanding something ?

**Comment by mpost** [comment] 2017-03-01 13:11
You will not need the workaround that @cpetrov described here as the ui will always relayout.

**Comment by natanraj** [comment] 2017-03-01 13:51
@mpost  Thanks I am using tabris 2.0.01-beta in my app. And the issue is still reflecting. 

Whereas in my tabris-2 scratchpad taken from  in Play doesn't have this issue. Does this mean the beta is yet to reflect this relayout ?

**Comment by natanraj** [comment] 2017-03-01 13:54
Attaching the screenshots
![preopening showing bottom textfields](https://cloud.githubusercontent.com/assets/11765325/23462648/ab0ef92e-feb4-11e6-851c-8c906fefa897.png)
![focus on text field doesnt move up](https://cloud.githubusercontent.com/assets/11765325/23462658/b2c118fa-feb4-11e6-96d4-2cfb983fcdc6.png)

**Comment by natanraj** [comment] 2017-03-01 13:56
On the appreciatory note 👍  I love Tabris.Js so far, for the simple and versatile framework it offers for small developers like me.. Keep it up 👍

**Comment by mpost** [comment] 2017-03-01 14:09
@natanraj Oh, my mistake. The change to always relayout the the ui when the keyboard opens is available in the 2.x-nightly but didn't make it into the 2.0.0-beta1. It will be in the 2.0.0-beta2 which is scheduled for next week.

**Comment by natanraj** [comment] 2017-03-07 14:15
@mpost is it released now ?

**Comment by mpost** [comment] 2017-03-08 13:14
@natanraj the beta2 is not out yet. we are putting the final touches on it. you can already use it by switching to the nightly builds of course.

**Comment by natanraj** [comment] 2017-05-23 01:20
@mpost I am having issues in setting the focus for the text input fields; The simple below one is not able to get the right focus on any of the below input fields. I am planning get inputs from text fields and have a bottom fixed buttons in a container. The container always overflows the text fields.

```
let txName = new tabris.TextInput().appendTo(myPage);
txName.layoutData = {top:200, centerX:0, width: 200};

let txArea = new tabris.TextInput().appendTo(myPage);
txArea.layoutData = {top:'prev()', centerX:0, width: 200};


let myUserActionsContainer = new tabris.Composite({background:'green'}).appendTo(myPage);
myUserActionsContainer.layoutData = {bottom:0, centerX:0, width:100, height: 100};
```

**Comment by cookieguru** [comment] 2017-05-23 02:02
@natanraj It's not clear what you're trying to achieve or how this relates to the `focus()` method.

**Comment by natanraj** [comment] 2017-05-23 02:08
@cookieguru My bad, if the word focus misinterpretted. the screen relayout is not going to the textField where it is  focused.

**Comment by natanraj** [comment] 2017-05-23 11:32
@mpost / @cookieguru Sorry if I am following up too much. Is there any workaround possible?

**Comment by mpost** [comment] 2017-06-01 09:06
@natanraj In Tabris.js 2 we will always resize the `tabris.ui.contentView` when the keyboard opens. therefore you will have full control over your layout.

**Comment by mpost** [comment] 2017-06-14 13:09
Closing this one as we know always resize the tabris.ui.contentView when the keyboard opens.

**Closed by mpost** 2017-06-14 13:09 UTC
Labels: feature
