### ISSUE TITLE
Improve performance of CollectionView with bunch of images Grid

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1859] opened 2019-04-19 14:01 UTC
Poor performance scroll with CollectionView of grid images(images > 400)
Second Point: Each time that updateCell() occur i need to put the scaleMode to the image because they loose it despite the fact that I did it at the creation of the images.
How can i have a great performance with CollectionView
TabrisJs 3.0.0Beta2 
Android 8
``` JAVASCRIPT
const {contentView,CollectionView,ImageView,Composite} = require('tabris');
const imagesPath = [{imagePath:'https://i.imgur.com/TCtLXpZ.jpg'},{imagePath:'https://i.imgur.com/mv8YkiP.jpg'},{imagePath:'https://i.imgur.com/sdXEBRl.jpg'},{imagePath:'https://drscdn.500px.org/photo/158789295/m%3D900_s%3D1_k%3D1_a%3D1/v2?webp=true&v=3&sig=4bd95aa2cbed8d94e29e9500ea545296b2001ffc70b59f515d187d9ad4ad42e9'},{imagePath:'https://drscdn.500px.org/photo/143776291/m%3D900_s%3D1_k%3D1_a%3D1/v2?webp=true&v=9&sig=738d4eefd84eb9f38940ba7742fb9c24215f0be8cd87fc8b4236f4b13d092fb1'},{imagePath:'https://sm.ign.com/ign_fr/news/c/captain-ma/captain-marvel-first-reactions-twitter-roundup_tse9.jpg'},{imagePath:'https://cdn-images-1.medium.com/max/2400/1*kqt8WntffBYIXRRzGCXWJg.png'},{imagePath:'http://www.maximumwall.com/wp-content/uploads/2017/01/wallpaper-image-compilation-janvier-2017-13-660x330.jpg'},{imagePath:'https://besthqwallpapers.com/Uploads/20-3-2018/44999/thumb2-green-abstraction-geometric-background-material-design-android-google.jpg'},{imagePath:'http://cdn.osxdaily.com/wp-content/uploads/2017/06/ios-11-default-wallpaper.jpg'},{imagePath:'https://boygeniusreport.files.wordpress.com/2018/11/iphone-xs-eraser-wallpaper.jpg'},{imagePath:'https://static.businessinsider.com/image/541acae669bedd94052c5ca4-750.jpg'},{imagePath:'http://getwallpapers.com/wallpaper/full/3/4/8/125042.jpg'},{imagePath:'https://www.iphoned.nl/wp-content/uploads/2018/07/ios-wallpapers1-580x375.jpg'},{imagePath:'https://www.setaswall.com/wp-content/uploads/2017/03/iOS10-stock-wallpaper-005.jpg'},{imagePath:'https://media.idownloadblog.com/wp-content/uploads/2018/11/iPad-Pro-11-advertising-wallpaper-3-light-blue.jpg'},{imagePath:'http://images6.fanpop.com/image/photos/41500000/Betta-Fish-betta-fish-41537774-1920-1080.png'}];
new CollectionView({layoutData:'fill',itemCount:imagesPath.length,columnCount:2,cellHeight:Number(screen.width / 2),
                          createCell: () => {
                            const cell = new Composite({width:Number(screen.width / 2),height:Number(screen.width / 2)});
                            new ImageView({scaleMode:'fill',width:Number(screen.width / 2),height:Number(screen.width / 2),id:'userPicture'}).appendTo(cell);
                          
                            return cell;
                          },updateCell: (cell,index) => {
                              const picture = cell.find('#userPicture')[0];
                              picture.image = imagesPath[index].imagePath;
                              
                          }
                        }).on('select', ({target,index}) =>{

                          console.log(imagesPath[index].imagePath);
                      }).appendTo(contentView); 
```

**Comment by cookieguru** [comment] 2019-05-07 23:11
This isn't performance related.  Also I believe this is a duplicate of #1502

**Comment by mpost** [comment] 2019-05-08 08:24
@ishigo1987 Thanks for bringing up the issue. Can you recreate the performance problem in a self contained snippet? The one you posted above does not run out of the box.

**Comment by ishigo1987** [comment] 2019-05-08 17:00
@mpost  with this new snippet update you can see the issue

**Comment by mpost** [comment] 2019-05-09 10:32
@ishigo1987 Thanks for the update. I have updated it again to work on tabris 3.x:

```js
import {CollectionView, Composite, contentView, ImageView} from 'tabris';

const imagesPath = [{imagePath: 'https://i.imgur.com/TCtLXpZ.jpg'}, {imagePath: 'https://i.imgur.com/mv8YkiP.jpg'}, {imagePath: 'https://i.imgur.com/sdXEBRl.jpg'}, {imagePath: 'https://drscdn.500px.org/photo/158789295/m%3D900_s%3D1_k%3D1_a%3D1/v2?webp=true&v=3&sig=4bd95aa2cbed8d94e29e9500ea545296b2001ffc70b59f515d187d9ad4ad42e9'}, {imagePath: 'https://drscdn.500px.org/photo/143776291/m%3D900_s%3D1_k%3D1_a%3D1/v2?webp=true&v=9&sig=738d4eefd84eb9f38940ba7742fb9c24215f0be8cd87fc8b4236f4b13d092fb1'}, {imagePath: 'https://sm.ign.com/ign_fr/news/c/captain-ma/captain-marvel-first-reactions-twitter-roundup_tse9.jpg'}, {imagePath: 'https://cdn-images-1.medium.com/max/2400/1*kqt8WntffBYIXRRzGCXWJg.png'}, {imagePath: 'http://www.maximumwall.com/wp-content/uploads/2017/01/wallpaper-image-compilation-janvier-2017-13-660x330.jpg'}, {imagePath: 'https://besthqwallpapers.com/Uploads/20-3-2018/44999/thumb2-green-abstraction-geometric-background-material-design-android-google.jpg'}, {imagePath: 'http://cdn.osxdaily.com/wp-content/uploads/2017/06/ios-11-default-wallpaper.jpg'}, {imagePath: 'https://boygeniusreport.files.wordpress.com/2018/11/iphone-xs-eraser-wallpaper.jpg'}, {imagePath: 'https://static.businessinsider.com/image/541acae669bedd94052c5ca4-750.jpg'}, {imagePath: 'http://getwallpapers.com/wallpaper/full/3/4/8/125042.jpg'}, {imagePath: 'https://www.iphoned.nl/wp-content/uploads/2018/07/ios-wallpapers1-580x375.jpg'}, {imagePath: 'https://www.setaswall.com/wp-content/uploads/2017/03/iOS10-stock-wallpaper-005.jpg'}, {imagePath: 'https://media.idownloadblog.com/wp-content/uploads/2018/11/iPad-Pro-11-advertising-wallpaper-3-light-blue.jpg'}, {imagePath: 'http://images6.fanpop.com/image/photos/41500000/Betta-Fish-betta-fish-41537774-1920-1080.png'}];

const screen = {width: 200, height: 200};

new CollectionView({
  layoutData: 'stretch', itemCount: imagesPath.length, columnCount: 2, cellHeight: screen.width / 2,
  createCell: () => {
    const cell = new Composite({width: screen.width / 2, height: screen.width / 2});
    new ImageView({
      scaleMode: 'fit',
      width: screen.width / 2,
      height: screen.width / 2,
      id: 'userPicture'
    }).appendTo(cell);

    return cell;
  }, updateCell: (cell, index) => {
    const picture = cell.find('#userPicture')[0];
    picture.image = imagesPath[index].imagePath;

  }
}).on('select', ({target, index}) => {

  console.log(imagesPath[index].imagePath);
}).appendTo(contentView);
```
With this change i could reproduce the scaleMode issue. We will look into it. Scroll performance was good for me although some images took a long time to load.

**Comment by mpost** [comment] 2019-05-09 13:37
@ishigo1987 One more note in regards to performance, since some of these images are very large, you should set the bounds of the image object to inform the system that the image can be physically resized. Thereby you will get better performance when scrolling.

```js
cell.find(ImageView).only().image = {src: imagesPath[index].imagePath, width: cellHeight, height: cellHeight};
```

**Closed** 2019-05-09 13:43 UTC

**Comment by ishigo1987** [comment] 2019-05-09 15:17
ok i make the change and i let you know

**Comment by ishigo1987** [comment] 2019-05-09 15:27
i have a lot of errors when i try to use only() and layoutData:'stretch'
Apparently @mpost  all this things is not available inside tabrisjs 3.0.0 beta2 
what's is the last version of tabrisJs 3x?

**Comment by cookieguru** [comment] 2019-05-09 15:30
@ishigo1987 Visit https://www.npmjs.com/package/tabris and click the Versions tab

**Comment by mpost** [comment] 2019-05-09 15:32
you can just switch to `nightly`

**Comment by ishigo1987** [comment] 2019-05-09 16:11
ok give me please the line
"tabris": "what i'm asking for"

**Comment by mpost** [comment] 2019-05-09 16:12
`nightly`.

But the fix is in the native platform. not in the js part.

**Comment by cookieguru** [comment] 2019-05-09 16:12
Just like @mpost said:
```plain
"tabris": "nightly"
```

**Comment by mpost** [comment] 2019-05-09 16:18
While the implemented fix did resolve the scaling issue, it created a different problem, where you could scroll the image if it would be shown larger than the `ImageView` bounds. We will fix this asap.

**Comment by ishigo1987** [comment] 2019-05-09 17:52
Ok thank you

**Comment by ishigo1987** [comment] 2019-05-09 19:48
Wooohhh all my code written with tabrisjs 3.0.0 beta2 returns error with nightly
i guess i will continue with beta 2 until the final 3.0.0 release

**Comment by cookieguru** [comment] 2019-05-09 19:58
@ishigo1987 What are the errors?  Have you looked at the [Migration Guide](https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md)?

**Comment by ishigo1987** [comment] 2019-05-09 20:03
no thank you i'm going to look the migration guide first

**Comment by ishigo1987** [comment] 2019-05-09 21:16
@cookieguru  @mpost 
this const navigationView = new NavigationView({layoutData:'fill', toolbarVisible:false,id:'homeView',class:'activeView'}).appendTo(contentView);
report me an error
could not load main module:Error Not an object: String at create
this was working on tabrisjs 3.0.0 beta2

**Comment by cookieguru** [comment] 2019-05-09 22:03
@ishigo1987 Is your native version the same as the JS version?

**Comment by ishigo1987** [comment] 2019-05-09 22:04
I guess it's the online build
And the only think that i update inside my package.json is "tabris":"nightly"
Do i need to do extra things?

**Comment by cookieguru** [comment] 2019-05-09 22:12
Yes, the native version needs to match the JS version *exactly*.  If you are using the nightlies this means you'll need to build a binary containing that same version.  With the online build select `latest`; local build does this automatically.

**Comment by ishigo1987** [comment] 2019-05-09 22:18
Ok but by default the online build tabrisjs client version is latest

**Comment by ishigo1987** [comment] 2019-05-09 22:21
Another think is textInputs they looks differents(border and label)this is an unwanted behavior for my design what's the style properties of textInput

**Comment by ishigo1987** [comment] 2019-05-09 22:22
I want to remove all this things and continue to have a invisible textInput 
With background:"transparent" like before

**Comment by cookieguru** [comment] 2019-05-09 22:56
The design of `TextInput`s has changed.  You should refer to [the docs](http://docs.tabris.com/3.0-beta2/) for more information.

All of this is much beyond the original issue with a `CollectionView`.

**Comment by ishigo1987** [comment] 2019-05-10 05:59
Nothing mention the fact that the textinput have changed inside your documentation link

**Comment by mpost** [comment] 2019-05-13 07:57
@ishigo1987 The changes are descibed in details in the migration-guide. You are running a nightly build which is great, to provide feedback but it is not yet released, therefore the docs migration guide needs to be consulted from the master branch. Btw... please don't reuse dormant issue for unrelated topics. Thank you. :)

**Comment by mpost** [comment] 2019-05-13 07:58
https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md#textinput-property-fillcolor-removed

**Comment by ishigo1987** [comment] 2019-05-13 08:29
@mpost  ok

**Comment by mpost** [comment] 2019-05-14 14:36
We have fixed the ImageView scaleMode/zoomable issue.

**Comment by ishigo1987** [comment] 2019-05-14 14:45
Thank you
