### ISSUE TITLE
Picker background inconsistent across platforms

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#612] opened 2015-09-02 13:41 UTC
```javascript
var page = tabris.create("Page", {topLevel: true, background: "blue"}).open();

var picker = tabris.create("Picker", {
  items: ["some item", "another item"], 
  layoutData: {left: 0, top: 0}
}).appendTo(page);
```

On Android `Picker`s appear transparent with black text. On iOS the widget is white with black text. The appearance of `Picker` may need to be unified on both platforms.

**Comment by mpost** [comment] 2015-09-02 13:42
Isn't that the particular native appearance on both platforms?

**Comment by mpost** [comment] 2015-12-11 13:46
Closing as "works as intended". The platform specific themes are honored in that case.

**Closed by mpost** 2015-12-11 13:46 UTC
Labels: bug
