### ISSUE TITLE
gzip-encoded responses cannot be parsed

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1360] opened 2017-05-26 12:44 UTC
### Problem description

- Actual Behavior: when parsing a gzip-encoded response, an error is thrown:
```
SyntaxError: Unexpected token in JSON at position 0
```
- Expected Behavior: gzip-encoded responses should be parsable

### Environment

- Device (name and OS version): Emulator, Android 7.1.1
- Tabris.js version: 2.0.0 nightly (26.05.2017)

### Code snippet

```javascript
  fetch('http://httpbin.org/gzip', {headers: {'Accept-Encoding': 'gzip'}})
    .then(response => response.json())
    .then(json => console.log(json))
    .catch(err => console.error(err));
```

**Comment by jonek** [comment] 2017-05-26 15:31
Using XHR instead of fetch works as expected in the case of the error above.

**Comment by cpetrov** [comment] 2017-05-26 15:52
When logging the response object:

```js
  fetch('http://httpbin.org/gzip', {headers: {'Accept-Encoding': 'gzip'}})
    .then(response => console.log(response))
    .catch(err => console.error(err));
```

... different results are observed pre- and post- 46572f8e7d3b56280f7ba91ba6f7133ff0e6a8d0:

|beta2|nightly (26.05.2017)|
|---|---|
|![screenshot_1495813689](https://cloud.githubusercontent.com/assets/2341769/26502047/9d5678e6-423b-11e7-8498-07dabcc63519.png) | ![screenshot_1495813713](https://cloud.githubusercontent.com/assets/2341769/26502049/9f41c9bc-423b-11e7-82f6-b0de9ca625c0.png)|

For beta2, calling `response.json()` also results in `SyntaxError: Unexpected token in JSON at position 0`.

**Comment by ralfstx** [comment] 2017-05-30 08:42
The Android implementation of `tabris.HttpRequest` does not unzip gzip encoded responses. It should do so since this is the expected behavior of the XHR and fetch APIs.

**Comment by irbull** [comment] 2017-05-30 16:17
I have looked at this, and the input stream is wrapped in a `GZIPInputStream` if `gzip` encoding is set. However, this doesn't work on `ByteBuffers` [1]. We will have to process the data in an intermediate stream and write the uncompressed data to the byte buffer. I can do this.

[1] https://stackoverflow.com/questions/8766351/compression-on-java-nio-direct-buffers

**Comment by mpost** [comment] 2017-06-14 08:30
Closing as resolved.

**Closed by mpost** 2017-06-14 08:30 UTC
Labels: Android, bug, priority: high
