### ISSUE TITLE
"This App May Slow Down Your iPhone"on iOS 10.1.1

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#1034] opened 2016-11-07 20:24 UTC
anyone else seeing this on iOS 10.1.1? it could be one of the plugins we're using but I just want to make sure its not how tabris is building the app

thanks

**Comment by patrykmol** [comment] 2016-11-08 09:15
We have never experienced this warning when using the Tabris.js App. It might one of the plugins as you have stated.

**Comment by bFlood** [comment] 2016-11-08 12:40
thanks @patrykmol I'll start looking at the plugins

**Comment by cpetrov** [comment] 2016-11-08 13:50
This seems to be related to using 32-bit architecture: http://gadgets.ndtv.com/apps/news/ios-10-1-adds-app-may-slow-down-your-iphone-warning-for-32-bit-apps-1524181

**Comment by mpost** [comment] 2016-11-11 13:01
Closing this for now. If you see the warning in a "vanilla" Tabris.js app please let us know.

**Comment by bFlood** [comment] 2017-08-15 17:54
I still see this warning but only for debug builds. release builds install fine. I've never been able to identify a plugin that is causing it, has anyone else seen this

on other forums, I've seen that adding the "release" flag to the build solved the issue but I can't confim it other then the release builds seem to work fine

for iOS 11 (beta), you can't even install apps with this warning so it would be a development/debugging issue going forward

**Comment by karolszafranski** [comment] 2017-08-22 09:36
@bFlood If you go to Settings -> About -> General do you see your app there on the "No updates available" list?

https://cdn2.macworld.co.uk/cmsdata/features/3660434/which-apps-wont-work-in-ios-11-settings_thumb.jpg

How do you build your app?

**Comment by bFlood** [comment] 2017-08-23 13:47
1. there is no arrow on the "applications" menu item, so I cannot view the list. I tried to install the debug version of my app after the iOS 11 beta was already installed. the installation process just stops. A disabled icon remains but when you try to launch it, a single alert dialog says: "XYZ needs to be Updated" and "This app needs to be updated by the developer to work on this version of iOS". If I install the release version, everything works as expected, its only the debug version that causes the issue

2. I'm using the tabris build servers (v1.10.0). fwiw, I can't use v1.x.nightly because this issue is still present: https://github.com/eclipsesource/tabris-js/issues/1256

**Comment by bFlood** [comment] 2017-09-12 16:39
any word on this?

**Comment by karolszafranski** [comment] 2017-09-14 06:12
I can only tell that build settings passed to the compiler should be:
```
    ARCHS = armv7 arm64
    VALID_ARCHS = armv7 arm64
```

You should be able to get those by using `--release` flag when building with cordova.

Are there `ARCHS` or `VALID_ARCHS` strings in build logs of your apps? If yes, what are the values for these parameters?

**Comment by bFlood** [comment] 2017-09-14 12:06
I am using the tabris build servers, do we access to those values from there? specifically when the Debug option is turned on for apps:

![image](https://user-images.githubusercontent.com/404991/30428946-9c944fa2-9923-11e7-9171-8b5d81f7368a.png)

**Comment by cpetrov** [comment] 2017-09-14 15:06
@bFlood 
The values of the variables `ARCHS` and `VALID_ARCHS` used for the build should be output in the build log. You can access the build log by clicking on the link for the particular build ID:

<img width="487" alt="pic1" src="https://user-images.githubusercontent.com/2341769/30437327-9a029316-996e-11e7-8578-cf140d67f720.png">

... and then selecting _Detailed Log_ on the page of this build:

<img width="655" alt="pic2" src="https://user-images.githubusercontent.com/2341769/30437349-a9de72be-996e-11e7-918b-85208fd52d36.png">

**Comment by bFlood** [comment] 2017-09-14 15:13
thank you, I use those logs all the time. Can you confirm an app from tabris build servers, with Debug configuration installs on iOS11? 

this app does not install on iOS11, from the detailed log:

``` log
Reading build config file:
Building project  : /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile.xcodeproj
	Configuration : Debug
	Platform      : device
Build settings from command line:
    ARCHS = armv7 arm64
    CONFIGURATION_BUILD_DIR = /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device
    SDKROOT = iphoneos9.3
    SHARED_PRECOMPS_DIR = /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/sharedpch
    VALID_ARCHS = armv7 arm64
```

**Comment by bFlood** [comment] 2017-10-23 13:56
bump - this is still an issue...

**Comment by bFlood** [comment] 2017-10-30 14:32
@cpetrov - I would really appreciate and answer on this. can you please try to build a debug version from 1.10.0 and see if you can install on ios11? does it work with 2.0?

**Comment by cpetrov** [comment] 2017-10-30 15:28
Hello @bFlood, I can confirm the issue when building a 1.10.0 app. It does not affect 1.x-nightly and 2.x builds though. Is https://github.com/eclipsesource/tabris-js/issues/1256 still an issue for you?

**Comment by bFlood** [comment] 2017-10-30 16:23
thank you for the response. yes, https://github.com/eclipsesource/tabris-js/issues/1256 is still an issue, so I cannot use 1.x-nightly

fwiw, we just had to create our annual developer code cert for apple, so the test I just ran was with a new cert and new provisioning profile. works on 1.1.0, fails on 1.x-nightly

**Comment by bFlood** [comment] 2017-11-06 21:15
1.10.0 Release builds will not install on iOS11 now

**Comment by bFlood** [comment] 2017-11-06 21:41
sorry, 1.10.0 Release builds are still installing on iOS11, the issue is with Debug builds

**Comment by mpost** [comment] 2018-06-14 08:50
Closing this for now. Please reopen if still applicable.

**Closed by mpost** 2018-06-14 08:50 UTC
