### ISSUE TITLE
Barcode Scanning Not Working v3 developer app

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1835] opened 2019-03-23 03:37 UTC
### Problem description

Scanning barcode failed with error undefined.

### Expected behavior

Scan and download playground code.

### Environment

- Tabris.js version: 3.0
- Device: Samsung Galaxy Grand Prime Plus
- OS: Android 6

**Comment by cookieguru** [comment] 2019-03-23 04:34
Duplicate of #1805

**Comment by mpost** [comment] 2019-03-26 09:15
Yes that is very likely a duplicate. I am closing this issue for now. Please add a comment with your device name on the issue #1805.

**Closed by mpost** 2019-03-26 09:15 UTC
