### ISSUE TITLE
ScrollView doesn't resize properly on iOS

### ISSUE THREAD

**Issue by anthonyvespoli** [eclipsesource/tabris-js#1156] opened 2017-02-28 21:50 UTC
If I have a scrollview without a defined height (left:0, top:0, bottom: 0, right:0) and I dynamically add new components to it after it has already been appended to the page, it doesn't resize itself and cuts off everything beyond it's initial height. This is also the case when I have a scrollview full of components that change height, such as an accordion...

Are there any decent workarounds for this? This has been a known issue for a while, can we expect a fix in the near future?

I saw a workaround in a similar issue was to rotate the device to force a resize. This option is not valid for me as I don't allow users to use landscape... Anyone??

Currently using 1.9

**Comment by cookieguru** [comment] 2017-02-28 21:55
Sounds like a duplicate of #846.  [The workaround](https://github.com/eclipsesource/tabris-js/commit/2035d9ac23005b2da186a64c9c57bc38b344e32e#diff-f8ca96967d33d69c6003b405cadae40dR70) is re-setting the bounds, not the screen orientation.

**Comment by anthonyvespoli** [comment] 2017-02-28 22:54
That solution doesn't work for me. Here is a very basic snippet of what I'm trying to do. When the user taps on the button it should append a blue composite to the scrollview. It works on the first tap, but any subsequent taps after don't appear to do anything. When I enter the debug view hierarchy in xcode and display clipped views I can see all the blue composites that are getting clipped because the scrollview isn't resizing. 

```
var addBlock = ()=>{
  return new Composite({
    layoutData: {left:0, right:0, top: 'prev()', height: 30},
    background: "blue"
  });
};

let scrollView = new ScrollView({
  layoutData: {left:0, right: 0, top: 0, bottom:50},
  direction: 'vertical',
  background: 'yellow'
}).appendTo(page);

var resetView = ()=>{
  scrollView.set({left: 0, right:0, top: 0, bottom: 50});
};

let button = new Composite({
  layoutData: {bottom: 0, width: 70, height: 30},
  background: 'green'
}).on('tap', ()=>{
  scrollView.append(addBlock());
  resetView();
  setTimeout(()=>{
    resetView();
  }, 10);
}).appendTo(page);
 ```

**Comment by cookieguru** [comment] 2017-02-28 23:01
Does it work in Android?  I.e. is it the same issue as https://github.com/eclipsesource/tabris-js/issues/936#issuecomment-281764266?

**Comment by anthonyvespoli** [comment] 2017-02-28 23:08
Yes it is the same issue

**Comment by frh3ddy** [comment] 2017-03-01 02:41
If you Append a TextViews instead of Composites it works as expected. a workaround would be to always keep a textview at the end, to someone force the ScrollView to resize, its what I did to make it work,

**Comment by mpost** [comment] 2017-03-01 13:08
I think we are looking at the same problem as @cookieguru linked with https://github.com/eclipsesource/tabris-js/issues/936. On iOS the `ScrollView` is not a complete Composite replacement yet as it does not grow its own intrinsic size.

We will fix this issue hopefully soon. Until than bottom attaching the `ScrollView` should work around the problem.

**Comment by anthonyvespoli** [comment] 2017-03-02 17:02
I was able to get this working by appending and removing a textview to the bottom of the scrollview after i add a new component or the height of an existing component changes. I just call this function after each append

```
            var resizeScrollView = (view: ScrollView, horizontal: boolean)=>{
                setTimeout(()=>{
                    if(horizontal){
                        new TextView({
                            layoutData: {left: 'prev()', top:0, bottom:0, width: 1},
                            text: ' '
                        }).on('resize', (w)=>{
                            w.dispose();
                        }).appendTo(view);
                    } else {
                        new TextView({
                            layoutData: {left: 0, top:'prev()', right:0, height: 1},
                            text: ' '
                        }).on('resize', (w)=>{
                            w.dispose();
                        }).appendTo(view);
                    }
                },100);
            };
```

**Comment by mpost** [comment] 2017-06-14 10:34
Closing it as resolved. Please reopen if you have any more problems.

**Closed by mpost** 2017-06-14 10:34 UTC
Labels: bug, ios
