### ISSUE TITLE
Nested TextView text is not aligned correctly as expected

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1250] opened 2017-04-20 11:35 UTC
### Problem description

We create a TextView, position it in the right bound of its parent widget and don't specify the width. Its size will be calculated according to the text size. Then we create another TextView that needs to be positioned between left bound and the previous TextView. In that case, the width of the right TextView is not calculated correctly. 

### Expected behavior

Create any widget between left bound and the right TextView must not affect to the width of the right TextView.

### Environment

- Tabris.js version: 2.1
- Device: iPhone 6
- OS: iOS 11.0

### Code snippet

```javascript
import {Composite, TextView, ui} from 'tabris';

new Composite({class: 'container', left: 0, right: 0, centerY: 0}).append(
  new TextView({
    class: 'right',
    text: 'Right text',
    right: 0, top: 0,
    background: 'rgba(255, 255, 0, 0.3)'
  }),
  new TextView({
    class: 'left',
    text: 'Left text',
    left: 0, top: 0, right: ['.right', 8],
    background: 'rgba(0, 255, 255, 0.3)'
  })
).appendTo(ui.contentView);
```

It works as expected in Android:
![first](https://cloud.githubusercontent.com/assets/13982125/25228813/dd267530-25de-11e7-962e-d32d7970e1e6.png)

The issue in iOS:
![second](https://cloud.githubusercontent.com/assets/13982125/25228832/ef0cc970-25de-11e7-96de-553b74276f3b.png)

**Comment by karolszafranski** [comment] 2017-04-20 14:58
Fixed in tabris-ios with a9491652142673e91c835426a59e6e268d5d05d9

![simulator screen shot 20 apr 2017 16 57 17](https://cloud.githubusercontent.com/assets/1746396/25237300/884090b2-25ea-11e7-8bbe-8f02b258fa88.png)

**Comment by elshadsm** [comment] 2017-10-07 20:24
The same problem happens again in Tabris 2.1.

**Comment by karolszafranski** [comment] 2017-10-19 14:42
Is the code snippet still valid for the issue? I did try `nightly` and `2.1.1`, `2.1.0` with snippet above, and I was not able to reproduce the issue.

I also built https://github.com/eclipsesource/tabris-js-hello-world with your code snipped as contents of `src/app.ts` with following platforms: https://tabrisjs.com/api/v1/downloads/2.1.0/ios
https://tabrisjs.com/api/v1/downloads/2.1.1/ios

How can I reproduce it?

**Comment by elshadsm** [comment] 2017-10-19 14:53
<img width="375" alt="ios" src="https://user-images.githubusercontent.com/13982125/31777272-bd940624-b4fe-11e7-8c3e-458c219e0e3b.png">

**Comment by elshadsm** [comment] 2017-10-19 14:54
However, I can reproduce the issue with Tabris.js `2.1.1` version.

**Closed** 2017-10-23 06:16 UTC
Labels: bug, ios
