### ISSUE TITLE
Transformations on widget creation influences layout on ios

### ISSUE THREAD

**Issue by dbuschtoens** [eclipsesource/tabris-js#1069] opened 2016-12-14 14:25 UTC
When a transformation is supplied in the constructor of a widget or applied directly after creation, the layout is created based on the location and size of the transformed widget rather than the base location and size of the widget.
This is problematic for example if you wish to animate the appearence of a widget using a translation or a size transform while other widgets are created, whose layout depends on the animated widgets.
Additionally, if the widget in question is a composite, layouts inside the composite that use the centerX or centerY properties will not work if the transformation has a scaling component.
A simple workaround is setting the transform using `setTimeout(()=>widget.set('transform',[...]), 0)` instead of setting the transform directly.

**Comment by patrykmol** [comment] 2019-10-09 14:44
I am unable to reproduce it with following snippet:
```
const testComposite = new Composite({
  top: 0,
  right: 0,
  height: 50,
  width: 100,
  background: 'red'
});
contentView.append(testComposite);

console.log("pre ", testComposite.absoluteBounds);
testComposite.transform = {translationY: 250}
console.log("post ", testComposite.absoluteBounds);
```

The snippet produces following output:
![Simulator Screen Shot - iPhone 8 - 2019-10-09 at 16 43 20](https://user-images.githubusercontent.com/12428999/66492045-0cb96400-eab4-11e9-95ed-245823ad96a9.png)
Closing.

**Closed by patrykmol** 2019-10-09 14:44 UTC
Labels: bug, ios

**Comment by fax1ty** [comment] 2019-10-09 20:41
@patrykmol
If I understood correctly, also recently asked about a similar problem
![](https://i.imgur.com/6RPdfWj.jpg)
