### ISSUE TITLE
Issue with ActionSheet

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1871] opened 2019-05-16 13:34 UTC
if the navigationBar background is set with a color, and the actionsheet widget is call;during the time that it's on screen the navigationBar background become black
The right behavior would be that the navigationBar keep his background color set

**Comment by mpost** [comment] 2019-05-16 16:13
@ishigo1987 That is a worthy observation but as usual i'll now ask for all the details that are in the issue template of this repo.

**Comment by ishigo1987** [comment] 2019-05-16 16:30
Ok i will give you a snippet

**Comment by ishigo1987** [comment] 2019-05-16 16:31
```JAVASCRIPT
const {contentView,Button,ActionSheet,navigationBar} = require('tabris');
navigationBar.background = '#eeeeee';
new Button({centerX:0,centerY:0,text:'Open Actionsheet'})
.onSelect(()=>{
  new ActionSheet({
        title:'Test',
        actions:[{title:"Action 1"},{title:"Action 2"}]
      }).open();
}).appendTo(contentView);



```

**Comment by mpost** [comment] 2019-05-17 09:41
what tabris version and platform do you see the issue on?

**Comment by mpost** [comment] 2019-05-17 09:43
This is actually the same issue as for the popover, which is an android fragment, similar to the actionsheet. See https://github.com/eclipsesource/tabris-js/issues/1870

**Comment by mpost** [comment] 2019-05-20 14:37
The behavior works as expected. Setting eg `'red'` to the `navigationBar` shows that the entire area behind the `ActionSheet` is darkened, including the nav and status bar. You therefore see a darker red tone on the navbar.

Since this is the system behavior i am closing this as "works as intended". Feel free to reopen if you feel otherwise.

**Closed by mpost** 2019-05-20 14:37 UTC
