### ISSUE TITLE
Baseline alignment does not work when baseline target has fixed height

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1272] opened 2017-05-05 12:26 UTC
As can be seen in the navigationview-properties.js snippet, baseline aligning to a textview with a fixed height does not work.

**Comment by karolszafranski** [comment] 2017-05-10 14:44
duplicate of https://github.com/eclipsesource/tabris-js/issues/1272

**Closed by karolszafranski** 2017-05-10 14:44 UTC
Labels: iOS
