### ISSUE TITLE
Permission, first time requested return nothing

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2090] opened 2020-07-20 11:51 UTC
### Problem description
When you accept permission for the first time, the result of the promise is not returned.

### Expected behavior

result returned by the promise

### Environment

- Tabris.js version: 3.6.0-dev.20200720
- Device: Huawei P10 Lite
- OS: Android 8

### Code snippet

```js

const{permission} = require("tabris");

if (permission.isAuthorized('camera')) {
    console.log("Permission granted");   
} else {
    permission.requestAuthorization("camera").then((responseStatus) => {
        if (responseStatus !== "granted") {
            // Permission denied
        } else {
            console.log("Permission granted");
        }
    });
}

```

**Comment by mpost** [comment] 2020-07-20 12:43
Running you provided snippet works as expected. The result is contained in `responseStatus` as expected. Could you try with a fully reset app? Clear its storage and try the snippet.

**Comment by ishigo1987** [comment] 2020-07-20 12:46
It works because you already have the permission in question I think, try to delete the permission and make the request when the window comes up you click on the accept button you won't get an answer at that moment.

Yes i already reset the app and make another build
Try it on Android 8

**Comment by mpost** [comment] 2020-07-20 13:03
I was aware of the prerequisite to never have asked for the permission in the first place. That is why i recommended to try it with a fresh install (aka with a cleared storage). In that scenario the snippet worked as expected. Also on API level 28 (Android 8).

Are you able to reproduce the behavior on other devices as well?

**Comment by ishigo1987** [comment] 2020-07-20 13:05
I'll try to replicate this behaviour on other devices and I'll be back...

**Comment by ishigo1987** [comment] 2020-07-20 14:06
@mpost  same problem, i send you the apk used on Slack

**Comment by mpost** [comment] 2020-07-20 14:17
@ishigo1987 Thank. We could reproduce the issue with the apk. The error only occurs when launching from an app buid with the tabris cli. We will fix it for the 3.6 release.

**Comment by ishigo1987** [comment] 2020-07-20 14:19
Ok thank you

**Comment by mpost** [comment] 2020-07-20 14:28
The problem is a bug in the cordova platform which does not correctly pass on the permission request result.

The issue has now been resolved in the latest `nightly` build. Please rebuild your app to verify the behavior.

**Closed by mpost** 2020-07-20 14:28 UTC
Labels: android, bug

**Comment by ishigo1987** [comment] 2020-07-20 14:29
Ok i do it right now

**Comment by ishigo1987** [comment] 2020-07-20 15:41
Problem solved thank you
