### ISSUE TITLE
Support getImageData() and putImageData() on Canvas

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#559] opened 2015-07-26 15:08 UTC
Tabris.js should support [getImageData()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) and [putImageData()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData) as defined on CanvasRenderingContext2D by the [HTML standard API](https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-getimagedata).

This feature was requested by @alpaca0984 in #556.

**Comment by jonek** [comment] 2015-07-26 15:14
This issue is also part of #92.

**Comment by bFlood** [comment] 2015-08-10 21:38
+1

**Comment by jonek** [comment] 2015-08-31 17:40
To fix this issue the following features and use cases should be implemented:
### reading pixel data from canvas
* introduce the `ImageData` type in Tabris.js as defined here: https://developer.mozilla.org/en-US/docs/Web/API/ImageData
* implement only `getImageData()` on the Tabris.js `CanvasContext` and let it return an `ImageData` object
### writing pixel datato canvas
**For now** we propose that drawing pixel data on a Canvas should Not be done via `putImageData()`. Instead we should support `CanvasContext.drawImage()` like defined here:
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage
The reason: the native Tabris.js implementations already support this method from Tabris (remote). It would be just a matter of "activating" it and providing appropriate JS API.

**Comment by bFlood** [comment] 2015-10-02 17:25
any movement on this? drawImage and getImageData would be great

**Comment by gosia-eclipsesource** [comment] 2015-10-05 12:40
We don't have an ETA yet for `getImageData()` but the `CanvasContext.drawImage()` part will most likely be included in Tabris.js 1.4. (1.3 is coming out this week)

**Comment by jonek** [comment] 2015-10-05 13:53
@bFlood If you have a specific use case for this feature we would be happy to hear about it. There are different ways how we can improve our current canvas implementation with regard to bitmaps. Just to make sure you will get what you really need.

**Comment by bFlood** [comment] 2015-10-05 14:45
thanks @jonek 

1. watermarking photos from the camera requires drawImage and then getImageData to get new the bitmap 

2. we use pdfmake (https://github.com/bpampuch/pdfmake ) for creating pdf files and sometimes we need to alter the images that go into them. again, getImageData is critical (also fwiw, https://github.com/eclipsesource/tabris-js/issues/377 blob support would also make the process more efficient, I'm still testing alternatives to blob saving )

3. drawImage/getImageData are useful for adding groundoverlays and custom markers to the map. drawing them client side and then using the base64 version for the marker is really helpful in many situations

thanks!

**Comment by bFlood** [comment] 2015-11-18 20:13
this wasn't added to 1.4, will it be in 1.5? is there a roadmap for tabris.js anywhere?

**Comment by gosia-eclipsesource** [comment] 2015-11-27 12:26
@bflood We'll provide an update on ImageData next week, also we'll be tracking the underlying blob support issue in #687.

**Comment by ralfstx** [comment] 2015-11-30 13:26
Image data are represented as a `Uint8ClampedArray`. Apparently, this type is supported by JavaScriptCore as well. @irbull How would we transfer typed arrays over the optimized CanvasContext protocol? Add another array to `packedOperations` that contains references? See [CanvasContext](/eclipsesource/tabris-js/blob/master/src/tabris/CanvasContext.js).

**Comment by gosia-eclipsesource** [comment] 2015-12-04 15:18
A draft implementation of ImageData on the JavaScript side is ready, now we need to use it on the clients. Probably not in this release but we'll try to finalize it soon.

**Comment by bFlood** [comment] 2016-01-06 13:11
will this be in tabris 1.6? we need to collect signatures from the app, works great but there is no way to get the image without getImageData

thanks!

**Comment by gosia-eclipsesource** [comment] 2016-01-08 15:39
@bFlood Sorry but it looks like it will be more work to get satisfying enough performance for imageData(). We should know more in the next 1-2 weeks.

**Comment by bFlood** [comment] 2016-01-08 15:45
ok, thanks for the update. fwiw, I would be happy with poor performance for now, better then nothing

**Comment by jkrause** [comment] 2016-01-15 10:20
It seems there is some morement in JSC to enable TypedArrays, see https://bugs.webkit.org/show_bug.cgi?id=120112

Until this becomes available we might be able to take advantage of this implementation:
https://github.com/phoboslab/Ejecta/blob/typed-array-clusterfuck/Source/Ejecta/EJConvertTypedArray.h
https://github.com/phoboslab/Ejecta/blob/typed-array-clusterfuck/Source/Ejecta/EJConvertTypedArray.m

Background on the implementation can be found here: http://phoboslab.org/log/2015/11/the-absolute-worst-way-to-read-typed-array-data-with-javascriptcore

**Comment by bFlood** [comment] 2016-01-15 13:30
thank you for the update, the background article was very interesting

for my use case (and maybe others), I don't really care about interacting with the array of pixels in JS, I just want a copy of the image. Would it be possible to add a simple toDataURL() method that returns a base64 copy of whatever was on the canvas? I think that would cover a lot of use cases where people would want to use getImageData() anyway. just a thought

**Comment by bFlood** [comment] 2016-02-25 17:36
bump

**Comment by gosia-eclipsesource** [comment] 2016-03-03 09:50
This feature is particularly difficult and requires input from several people in the team, we keep it on our radar but it won't be in the next release, sorry :(

**Comment by bFlood** [comment] 2016-03-03 13:38
how about just a simple save to file, then pass the filename back to javascript?

**Comment by mpost** [comment] 2016-03-22 09:16
Just wanted to let you know that we are looking into the issue and are making some good progress. No ETA just yet.

**Comment by bFlood** [comment] 2016-04-27 17:01
any chance this is in nightly yet? thx

**Comment by gosia-eclipsesource** [comment] 2016-04-28 09:44
@bFlood There's a pending change for Android but not in the nightly yet. Should be in next week.

**Comment by bFlood** [comment] 2016-04-28 18:09
thx, is the iOS code in nightly yet?

**Comment by gosia-eclipsesource** [comment] 2016-04-29 09:32
@bFlood Not there yet. The Android code will be in first.

**Comment by mpost** [comment] 2016-05-19 12:00
The support for imagedata has been added in tabris.js and android and can be used in from the 1.8 release one. We are still working on iOS support so we are not declaring it released yet.

**Comment by bFlood** [comment] 2016-05-19 13:04
thank you!

**Comment by trevorwat** [comment] 2016-05-22 18:44
+1 for the need to implement this - I wrestled with trying to get it to work on iOS before spotting it wasn't implemented.  Can I assume it will be in 1.9?

I have a use case where I'm planning to do OCR using OCRAD.js

**Comment by trevorwat** [comment] 2016-05-22 19:16
P.S. - just to check, this is the error I get in iOS from the canvas demo... this will fix it, right(?)

TypeError: Invalid array length argument
> Uint8ClampedArray@[native code]
getImageData@https://tabrisjs.com/api/v1/pins/574204a26508b0e4d7619762/node_modules/tabris/tabris.min.js:33:32027
https://tabrisjs.com/api/v1/pins/574204a26508b0e4d7619762/app.js:20:30
_callAll@https://tabrisjs.com/api/v1/pins/574204a26508b0e4d7619762/node_modules/tabris/tabris.min.js:32:9616
trigger@https://tabrisjs.com/api/v1/pins/574204a26508b0e4d7619762/node_modules/tabris/tabris.min.js:32:9441
trigger@https://tabrisjs.com/api/v1/pins/574204a26508b0e4d7619762/node_modules/tabris/tabris.min.js:32:54149
_trigger@https://tabrisjs.com/api/v1/pins/574204a26508b0e4d7619762/node_modules/tabris/tabris.min.js:32:27691
_notify@https://tabrisjs.com/api/v1/pins/574204a26508b0e4d7619762/node_modules/tabris/tabris.min.js:32:10390
_notify

If it does - please let me know how I get the updated version?

Thanks - and BTW, Tabris is awesome!

**Comment by trevorwat** [comment] 2016-05-31 23:09
Hi
I've managed to work around not having drawImage() for now by pre-preparing an imagedata array outside of the app... but could I check that drawImage() is definitely coming please? (as well as the pixel by pixel ImageData on IOS)?

I was able to get OCRAD to work, and some cool in-canvas image manipulation with imagefilters.js

Thanks.

**Comment by gosia-eclipsesource** [comment] 2016-06-01 11:34
Hi @trevorwat, interesting work! Sorry we missed your previous comments. We will try to include the iOS implementation in 1.9. Don't know yet about drawImage() but will get back to you about that.

**Comment by bFlood** [comment] 2016-06-01 11:46
drawImage() would be a really nice to have!

**Comment by trevorwat** [comment] 2016-06-01 20:41
Hi,

Ok great news – thanks.

drawImage would be good but I can work around it if I have to so long as get/put ImageData are there.

 

Thanks again!

 

 

 

 

Best regards,
Trevor

Trevor Watkins
____________________________
www.thoriumds.com <http://www.thoriumds.com/> 
trevor.watkins@thoriumds.com <mailto:trevor.watkins@thoriumds.com> 



  

‘The information in this e-mail (which includes any files transmitted with it) is confidential.  It is intended for the addressee only.  If this e-mail has been received by you and you are not the addressee please inform the sender and erase the e-mail from your system immediately.  Any use, re-transmission, forwarding or copying of this e-mail by anyone other than the addressee is prohibited. Copyright in this e-mail and any document created by us will be and remains our property and this e-mail does not transfer any rights to you. This e-mail and its contents may not be relied on for any purpose whatsoever by anyone other than the addressee and no liability will be accepted for any loss however arising caused by misuse of or unauthorised reliance on this e-mail.'

**Comment by mpost** [comment] 2017-01-17 15:14
Support for get and put ImageData has been added. Please see the canvas snippet for an example.

**Closed by mpost** 2017-01-17 15:14 UTC
Labels: feature, in progress
