### ISSUE TITLE
Add onDoubleTap event

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1928] opened 2019-08-22 19:56 UTC
Currently we have only [`tap`](https://docs.tabris.com/latest/api/Widget.html#tap) event. 
Please, add to `Widget`s [`doubleTap`](https://developer.android.com/reference/android/view/GestureDetector.OnDoubleTapListener) event

**Comment by cookieguru** [comment] 2019-08-22 20:06
#1172

**Comment by mpost** [comment] 2019-08-27 08:21
Closing this as duplicate of the mentioned #1172.

As a workaround you can use the `touchDown` event and track the time between two events. This will allow to you to get the same result.

**Closed by mpost** 2019-08-27 08:21 UTC
