### ISSUE TITLE
TextView alignment inside Composite without explicit width

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#1572] opened 2017-12-16 18:51 UTC
### Problem description

Same as issue #1250 which has been closed.
TextViews inside a Composite are not aligned correctly if the Composite does not have an explicit width (set using the right or width attributes). The code posted below shows that the widths of the TextViews are not set correctly even though the left and right attributes are both set to zero.

### Expected behavior

Width of TextViews should be set to the computed final width of the parent Composite. This would allow the alignment property on the TextBox to work correctly.

Code from the first section of the snippet should produce a similar result to the second section (i.e. the labels and the values should be next to each other).

### Environment

- Tabris.js version: 2.2.0
- Device: Samsung Note 8
- OS: Android 7.1.1

### Code snippet

```javascript
// Padding was added to make problem obvious but removing it makes no difference
const {Composite, TextView, ui} = require('tabris');

// This section creates blocks which are not correct
new Composite({background:'red', left:0, top:0, padding:4}).append(
	new TextView({alignment:'right', background:'white', left:0, right:0, text:'Label 1'}),
	new TextView({alignment:'right', background:'white', left:0, right:0, top:'prev()', text:'The Second Label'}),
	new TextView({alignment:'right', background:'white', left:0, right:0, top:'prev()', text:'Label 3'})
).appendTo(ui.contentView);

new Composite({background:'blue', left:'prev()', top:0, right:0, padding:4}).append(
	new TextView({alignment:'left', background:'white', left:0, right:0, text:'Value 1'}),
	new TextView({alignment:'left', background:'white', left:0, right:0, top:'prev()', text:'Value 2'}),
	new TextView({alignment:'left', background:'white', left:0, right:0, top:'prev()', text:'Value 3'})
).appendTo(ui.contentView);


// This section creates blocks which work correctly
new Composite({background:'red', left:0, top:200, padding:4, width:140}).append(
	new TextView({alignment:'right', background:'white', left:0, right:0, text:'Label 1'}),
	new TextView({alignment:'right', background:'white', left:0, right:0, top:'prev()', text:'The Second Label'}),
	new TextView({alignment:'right', background:'white', left:0, right:0, top:'prev()', text:'Label 3'})
).appendTo(ui.contentView);

new Composite({background:'blue', left:'prev()', top:200, right:0, padding:4}).append(
	new TextView({alignment:'left', background:'white', left:0, right:0, text:'Value 1'}),
	new TextView({alignment:'left', background:'white', left:0, right:0, top:'prev()', text:'Value 2'}),
	new TextView({alignment:'left', background:'white', left:0, right:0, top:'prev()', text:'Value 3'})
).appendTo(ui.contentView);
```

**Comment by mpost** [comment] 2017-12-18 10:02
Thanks for the report. Indeed in the first code block the Label 1 and 2 should span the entire width of the red parent.

**Comment by mpost** [comment] 2017-12-18 10:03
Btw, this is not the exact same issue than https://github.com/eclipsesource/tabris-js/issues/1250 which dealed with priorities when attaching to a side.

**Comment by mpost** [comment] 2017-12-18 17:09
The issue is actually related to the intrinsic behavior of the `ConstraintLayout` we use in Tabris.js on Android. An issue for it can be observed here: https://issuetracker.google.com/issues/37137034.

**Comment by mpost** [comment] 2020-04-29 10:56
Closing as resolved.

**Closed by mpost** 2020-04-29 10:56 UTC
Labels: android, bug
