### ISSUE TITLE
Collection view refresh indicator sometimes doesn't behave as expected

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#915] opened 2016-07-04 16:15 UTC
There are two cases in which the refresh indicator doesn't behave as expected on iOS:
1. A page containing a collection view with _refreshIndicator_ set to `true` gets opened. Then the indicator is shown, but not rotating. 
   
   To reproduce, tap on the _Open collection view page_ button in the example.
2. _refreshIndicator_ is set to true when the CollectionView already has items and the containing page is already opened. In this case, the refresh indicator is not shown at all. 
   
   To reproduce, tap on _Open collection view page_, tap on _Toggle refreshIndicator_ to hide the indicator and tap again to show it. No indicator will be visible. Gently pulling down on the collection view will reveal it.

``` javascript
var items = ["foo", "bar", "baz", "bad", "for", "bap", "bak", "foa"];

var welcomePage = new tabris.Page({
  title: "Welcome Page",
  topLevel: true
}).open();

new tabris.Button({
  centerX: 0, centerY: 0,
  text: "Open collection view page"
}).on("select", function() {
  page.open();
}).appendTo(welcomePage);

var page = new tabris.Page({
  title: "Collection View",
  topLevel: true
});

new tabris.Button({
  id: "button",
  left: 0, top: 0, right: 0,
  text: "Toggle refreshIndicator"
}).on("select", function() {
  collectionView.set("refreshIndicator", !collectionView.get("refreshIndicator"));
}).appendTo(page);

var collectionView = new tabris.CollectionView({
  layoutData: {left: 0, top: "#button", right: 0, bottom: 0},
  items: items,
  itemHeight: 256,
  refreshEnabled: true,
  refreshIndicator: true,
  initializeCell: function(cell) {
    var textView = new tabris.TextView({centerY: 0, centerX: 0}).appendTo(cell);
    cell.on("change:item", function(widget, item) {
      textView.set("text", item);
    });
  }
}).appendTo(page);
```

**Comment by patrykmol** [comment] 2017-05-12 10:03
This seems like a duplicate of https://github.com/eclipsesource/tabris-js/issues/1008 which is now fixed.

**Closed by patrykmol** 2017-05-12 10:03 UTC
Labels: bug, iOS
