### ISSUE TITLE
Canvas resets in collectionview when loading cell for second time

### ISSUE THREAD

**Issue by 3to1null** [eclipsesource/tabris-js#1183] opened 2017-03-10 13:02 UTC
Because it is not possible to create circles in android 4.4 using standard TabrisJS widgets, I use circles that are drawn in a canvas. Although it is a little more work, it works fine. 

The problem occurs when the collectionview gets bigger and (I think) and the canvas scrolls offscreen. When I scroll back the canvas is only drawn partially, or not at all.

**Comment by mpost** [comment] 2017-03-10 13:49
On what platform do you see the problem? Could you provide a snippet?

**Comment by 3to1null** [comment] 2017-03-10 14:32
I'm currently only developing for android.

this is the function that generates the the circle, `canvas` is the canvas it will be drawn in.
```
function generate_cijfer_circle(canvas, cijfer){
	var CANVAS_SIZE = 60;
	var ARC_RADIUS = 23;
	var context = canvas.getContext("2d", CANVAS_SIZE, CANVAS_SIZE);
	drawArc(12, 13, 0, 2.5, false);
	function drawArc(x, y, startAngle, endAngle, counterClockwise) {
		//context.font = "50px sans-serif";
		context.beginPath();
		context.moveTo(x + ARC_RADIUS, y + ARC_RADIUS);
		context.arc(x + ARC_RADIUS, y + ARC_RADIUS, ARC_RADIUS, startAngle * Math.PI, endAngle * Math.PI, counterClockwise);
		if(parseFloat(cijfer) < 5.5){
			context.fillStyle = colors.cijfer_onvoldoende;
		}else{
			context.fillStyle = colors.accent;
		}
		context.fill();
		context.fillStyle = colors.white_bg;
		context.textAlign = 'left';
		context.scale(1.8,1.8);
		if(String(cijfer) === "10.0"){
			context.fillText("10", (x / 1.8) + 6, y + ARC_RADIUS / 2 );
			
		}else if(String(cijfer) === "-" || (String(cijfer) == parseInt(cijfer)) && String(cijfer).substring(String(cijfer).length - 1, String(cijfer).length) !== "0"){
			context.fillText(cijfer, (x / 1.8) + 10, y + ARC_RADIUS / 2 );
		}else if(String(cijfer).length === 1){
			context.fillText(cijfer, (x / 1.8) + 8.8, y + ARC_RADIUS / 2);
		}else{
			context.fillText(cijfer, (x / 1.8) + 4.8, y + ARC_RADIUS / 2 );
		}
	}
}
```

this function is called in the initializeCell function after the canvas is created.

**Comment by cpetrov** [comment] 2017-03-17 13:44
@3to1null I guess `cijfer` should be a number? `fillText()` expects a string as its first parameter. I've changed your snippet accordingly. With the following snippet I could not reproduce your problem. Can you try if this works for you? (Tabris.js 2.x-beta2)

```js
const {ui, CollectionView, Canvas} = require('tabris');

new CollectionView({
  left: 0, top: 0, right: 0, bottom: 0,
  items: new Array(1000),
  itemHeight: 72,
  initializeCell: (cell) => {
    let canvas = new Canvas({left: 0, top: 0, right: 0, bottom: 0}).appendTo(cell);
    generate_cijfer_circle(canvas, Math.floor(Math.random() * 10) + 1);
  }
}).appendTo(ui.contentView);

function generate_cijfer_circle(canvas, cijfer) {
  const CANVAS_SIZE = 60;
  const ARC_RADIUS = 23;
  var context = canvas.getContext('2d', CANVAS_SIZE, CANVAS_SIZE);
  drawArc(12, 13, 0, 2.5, false);
  function drawArc(x, y, startAngle, endAngle, counterClockwise) {
    context.beginPath();
    context.moveTo(x + ARC_RADIUS, y + ARC_RADIUS);
    context.arc(x + ARC_RADIUS, y + ARC_RADIUS, ARC_RADIUS, startAngle * Math.PI, endAngle * Math.PI, counterClockwise);
    if(parseFloat(cijfer) < 5.5) {
      context.fillStyle = 'red';
    }else{
      context.fillStyle = 'blue';
    }
    context.fill();
    context.fillStyle = 'white';
    context.textAlign = 'left';
    context.scale(1.8,1.8);
    if(String(cijfer) === '10.0') {
      context.fillText('10', (x / 1.8) + 6, y + ARC_RADIUS / 2);
    } else if(String(cijfer) === '-' || (String(cijfer) == parseInt(cijfer)) && String(cijfer).substring(String(cijfer).length - 1, String(cijfer).length) !== '0') {
      context.fillText(cijfer.toString(), (x / 1.8) + 10, y + ARC_RADIUS / 2);
    }else if(String(cijfer).length === 1) {
      context.fillText(cijfer.toString(), (x / 1.8) + 8.8, y + ARC_RADIUS / 2);
    }else{
      context.fillText(cijfer.toString(), (x / 1.8) + 4.8, y + ARC_RADIUS / 2);
    }
  }
}
```

**Comment by 3to1null** [comment] 2017-03-18 11:10
I'm not yet using Tabris.js 2, but changing the changing `cijfer`  to a string did not change anything.

I think I did find the problem though, in every other collectionView with canvas created circles I create them in the initialize cell function, but for some reason I only created the canvas in InitializeCell while the contents (so the circle/drawing) were created in the `cell.on("change:item")` function.

I'm pretty young and don't have much experience, so I'm sorry for bothering you.

**Comment by cookieguru** [comment] 2017-03-19 01:30
@3to1null You'll want to keep the canvas initialization inside the `initializeCell` function.  The `CollectionView` is implemented using Android's [`RecyclerView`](https://developer.android.com/training/material/lists-cards.html) which re-uses cells on scrolling to save memory.
If the contents of your Canvas will be the same for every cell, move those to `initializeCell` as well so they don't have to be re-drawn as the user scrolls up and down the list.

**Comment by 3to1null** [comment] 2017-03-19 16:13
@cookieguru They are mostly the same (but not completely). I use the `cellType` to pass a var to the function that draws the canvas. I know that this is probably not recommended but it is the only way I can find.

**Comment by cookieguru** [comment] 2017-03-19 18:18
The only other way would be to look at other datapoints on the cell, and I don't know why `cellType` would be recommended any less than the others.

**Comment by mpost** [comment] 2017-06-14 10:17
Closing this one for now. Please reopen if you have any more issues.

**Closed by mpost** 2017-06-14 10:17 UTC
