### ISSUE TITLE
Need good guidance on tabris2/nightly/scratchpad

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1311] opened 2017-05-12 09:10 UTC
### Problem description
Unable to get the latest syntax per migration guide workig for collectionView on scratchpad
- Actual Behavior: collectionView is using old syntax in ScratchPad but nightly build expects them to have new syntax
- Expected Behavior: Scratchpad to support tabris2 syntax for collectionView.  

### Environment

- Device (name and OS version): 
- Tabris.js version: nightly

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:

```

**Comment by cookieguru** [comment] 2017-05-12 21:20
Duplicate of #1194

**Closed** 2017-05-13 14:59 UTC
Labels: bug

**Comment by natanraj** [comment] 2017-05-16 03:02
@ralfstx Please let us know what settings one has to use in Build settings & Dependencies. Hope ScratchPad is latest.

**Comment by cookieguru** [comment] 2017-05-16 03:03
@natanraj Check the other (linked) ticket you created

**Comment by ralfstx** [comment] 2017-05-16 07:57
@natanraj The scratchpad is currently bound to the latest development version, 2.0 RC 1.
Please note that you don't *have to* use the scratchpad to try out your snippets. You can easily serve them from your local machine using the [Tabris CLI](https://www.npmjs.com/package/tabris-cli).

**Comment by mpost** [comment] 2017-05-16 10:23
```shell
$ npm install -g tabris-cli
$ git clone https://github.com/eclipsesource/tabris-js.git
$ cd tabris-js/snippets
$ tabris serve button.js
```
