### ISSUE TITLE
Add support to implement a (background) service in Tabris.js

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#497] opened 2015-06-25 12:43 UTC
Can I build an app that runs in the background as Service

**Comment by mpost** [comment] 2015-06-30 09:22
Currently this is not possible. We are aware that it is a good addition to have and we are currently evaluating how to implement it.

**Comment by hstaudacher** [comment] 2015-06-30 09:25
@ruarch if you are talking about executing code when the app is in the background this is possible. You can react on pause and resume events, see https://tabrisjs.com/documentation/1.0/api/app

@mpost is talking about executing code in some kind of a background thread I think

**Comment by mpost** [comment] 2015-06-30 09:28
@hstaudacher Correct. I was referring to functionality that would be enabled by support something similar to a webworker.

**Comment by gosia-eclipsesource** [comment] 2015-07-27 09:55
Feel free to reopen this issue if you need more details.

**Comment by gosia-eclipsesource** [comment] 2015-08-05 15:36
Actually, this issue is a duplicate of #358.

**Closed by gosia-eclipsesource** 2015-08-05 15:36 UTC
Labels: feature
