### ISSUE TITLE
Canvas memory leak

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1716] opened 2018-08-02 10:41 UTC
### Problem description

When repeatedly creating a Canvas and calling `canvas.getContext()` after it has been laid out, the iOS app would eventually crash.

### Environment

- Tabris.js version: 2.5.1
- Device: iPad Air 
- OS: 11.2.2

### Code snippet

On this particular device, the app would crash after the ~160th iteration.

```javascript
const {TextView, Canvas, ui} = require('tabris');

const ITERATIONS = 10000;

let counterLabel = new TextView({bottom: 30, centerX: 0, text: '0'}).appendTo(ui.contentView);
let counter = 0;

draw();

function draw() {
  counter++;
  new Canvas({
    left: 10, top: 10, right: 10, bottom: 10
  }).on('resize', ({target: canvas, width, height}) => {
    canvas.getContext('2d', width, height);
    if (counter <= ITERATIONS) {
      counterLabel.text = counter;
      setTimeout(() => {
        canvas.dispose();
        draw();
      }, 10);
    }
  }).appendTo(ui.contentView);
}

```

**Comment by patrykmol** [comment] 2019-09-02 06:33
It seems that canvas' corresponding `GC` instance is not getting disposed. @tbuschto confirmed this.

**Comment by tbuschto** [comment] 2021-04-16 15:34
Duplicate of #2130

**Closed by tbuschto** 2021-04-16 15:34 UTC
Labels: bug, js
