### ISSUE TITLE
How to get a list of items in localstorage

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1715] opened 2018-07-27 13:24 UTC
It would be helpful while developing my app, to get a list of **all** items stored in `localstorage`

I know how to do this in a browser, but can't find a way to do it with tabrisjs (iOS **and** Android - since there is a difference )
~  thanks

**Ref:
-  (closed ticket) https://github.com/eclipsesource/tabris-js/issues/1709
- HTML5 method: https://stackoverflow.com/questions/5410745/how-can-i-get-a-list-of-the-items-stored-in-html-5-local-storage-from-javascript

**Comment by cookieguru** [comment] 2018-07-27 20:20
Currently this is not possible as the APIs necessary to retrieve all keys is not implemented: #313

**Comment by ishigo1987** [comment] 2018-08-21 08:45
I think that the best solution for you is to use just one localStorage and store the data inside with JSON.stringify(objectData)

**Comment by mrmccormack** [comment] 2018-08-21 12:44
Thanks... I see there is a 
 `localStorage.clear()` 
which *Remove all key/value pairs from the storage.* 

When testing apps, that is what I wanted to do, was to `clear` all key/value pairs.

**Comment by cookieguru** [comment] 2018-08-21 16:57
> I think that the best solution for you is to use just one localStorage and store the data inside with JSON.stringify(objectData)
This is a valid workaround, but the extra steps and time needed to do the (un)serialization make this a less than ideal solution.

**Comment by tbuschto** [comment] 2018-10-02 10:33
Duplicate of https://github.com/eclipsesource/tabris-js/issues/313

**Closed by tbuschto** 2018-10-02 10:33 UTC
