### ISSUE TITLE
Cannot access iOS build artifacts

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1056] opened 2016-12-03 10:14 UTC
`ipa`s get successfully built on http://tabrisjs.com , but when trying to download them, following XML is served instead:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>...</RequestId>
  <HostId>
    ...
  </HostId>
</Error>
```

**Comment by bFlood** [comment] 2016-12-05 13:56
can this be fixed? cannot install from the tabris build page, I get the same error as above

**Comment by fwaibel** [comment] 2016-12-05 16:18
We are currently investigating this issue. Seems to be a sporadic failure during the build on TravisCI.

**Comment by bFlood** [comment] 2016-12-07 15:24
fyi - I just ran another build and this is still an issue. thx

**Comment by bFlood** [comment] 2016-12-08 18:16
I can access the iOS builds now, thanks

did something change with the version number for builds? the values in my config.xml are not used anymore (iSO and Android)

**Comment by fwaibel** [comment] 2016-12-09 09:46
Glad you can access your iOS builds again.

Regarding the version number are you talking about the environment variable `BUILD_NUMBER`?

**Comment by bFlood** [comment] 2016-12-12 14:42
previously, the value in the config.xml (widget.version) was used in the tabris build UI, now it seems stuck on an older version number. maybe its just a UI bug

![image](https://cloud.githubusercontent.com/assets/404991/21102908/2d0f780e-c04e-11e6-9591-a62c11c50283.png)

**Comment by bFlood** [comment] 2016-12-12 15:29
also, fwiw, the release build versions lock up immediately on both iOS and Android. On iOS, these are in the error logs (not sure of they are relevant):

``` log
<Notice>: SandboxViolation: SDLMobile(456) deny(1) file-read-times /var
```

``` log
<Notice>: {"msg":"client getting effective client name", "clientName":"com.sdlportal.sdlmobile3", "bundleId":"", "bundlePath":""}
```

**Comment by fwaibel** [comment] 2016-12-12 16:06
I'll check the issue with the version number. Thanks for reporting.

Which Tabris.js Client Version are you using?

**Comment by bFlood** [comment] 2016-12-12 16:06
v1.10.0

**Comment by bFlood** [comment] 2016-12-12 19:20
the error on Android is:

``` log
12-12 14:17:51.706: E/Vold(308): Failed to find mounted volume for /storage/extSdCard/Android/data/com.sdlportal.sdlmobile3/files/
12-12 14:17:51.716: E/Vold(308): Failed to find mounted volume for /storage/extSdCard/Android/data/com.sdlportal.sdlmobile3/cache/
12-12 14:17:51.756: E/Parcel(910): Class not found when unmarshalling: com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp
12-12 14:17:51.756: E/Parcel(910): java.lang.ClassNotFoundException: com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp
12-12 14:17:51.756: E/Parcel(910): 	at java.lang.Class.classForName(Native Method)
12-12 14:17:51.756: E/Parcel(910): 	at java.lang.Class.forName(Class.java:309)
12-12 14:17:51.756: E/Parcel(910): 	at java.lang.Class.forName(Class.java:273)
12-12 14:17:51.756: E/Parcel(910): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
12-12 14:17:51.756: E/Parcel(910): 	at android.os.Parcel.readParcelable(Parcel.java:2245)
12-12 14:17:51.756: E/Parcel(910): 	at android.os.Parcel.readValue(Parcel.java:2152)
12-12 14:17:51.756: E/Parcel(910): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
12-12 14:17:51.756: E/Parcel(910): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
12-12 14:17:51.756: E/Parcel(910): 	at android.os.BaseBundle.getString(BaseBundle.java:918)
12-12 14:17:51.756: E/Parcel(910): 	at android.content.Intent.getStringExtra(Intent.java:5794)
12-12 14:17:51.756: E/Parcel(910): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2411)
12-12 14:17:51.756: E/Parcel(910): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1892)
12-12 14:17:51.756: E/Parcel(910): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5457)
12-12 14:17:51.756: E/Parcel(910): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5241)
12-12 14:17:51.756: E/Parcel(910): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:143)
12-12 14:17:51.756: E/Parcel(910): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3418)
12-12 14:17:51.756: E/Parcel(910): 	at android.os.Binder.execTransact(Binder.java:446)
12-12 14:17:51.756: E/Parcel(910): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
12-12 14:17:51.756: E/Parcel(910): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-12 14:17:51.756: E/Parcel(910): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
12-12 14:17:51.756: E/Parcel(910): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
12-12 14:17:51.756: E/Parcel(910): 	... 17 more
12-12 14:17:51.756: E/Parcel(910): 	Suppressed: java.lang.ClassNotFoundException: com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp
12-12 14:17:51.756: E/Parcel(910): 		at java.lang.Class.classForName(Native Method)
12-12 14:17:51.756: E/Parcel(910): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
12-12 14:17:51.756: E/Parcel(910): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
12-12 14:17:51.756: E/Parcel(910): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
12-12 14:17:51.756: E/Parcel(910): 		... 18 more
12-12 14:17:51.756: E/Parcel(910): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

```

**Comment by mpost** [comment] 2016-12-13 09:33
@bFlood could you completely uninstall the app (maybe even with `adb uninstall com.sdlportal.sdlmobile3`.

**Comment by fwaibel** [comment] 2016-12-13 09:35
I've never seen this particular one. Could you do a full uninstall, reinstall cycle to rule out any unwanted side effects?

**Comment by bFlood** [comment] 2016-12-13 13:40
@mpost I tried that, full uninstall and then reinstall. Same result. I've also tried it on 3 separate devices and get the same error. Also odd that the iOS build is not working either (but older release versions are working)

When I install an older build (coincidentally, a version before the version numbers above stopped working), it works as expected. All new Release versions for about the last  7 days do not work. Can you build Release versions and install them? Has anything changed on the build servers?

**Comment by bFlood** [comment] 2016-12-13 18:49
just checking in, can anyone build Release versions that work on the device? I'm stuck until this get sorted out

**Comment by bFlood** [comment] 2016-12-14 14:02
@mpost  @fwaibel  can you confirm release builds are working?

**Comment by fwaibel** [comment] 2016-12-14 14:06
@bFlood We checked several Android builds which are working fine. An iOS build has been uploaded to ITC. We'll post once this test is finished, too.

**Comment by bFlood** [comment] 2016-12-14 14:10
thank you. are the version numbers off on other accounts as well? 

what can I do next? I can't build new release versions and nothing has changed on my side, its the same code that worked fine 8 days ago

**Comment by fwaibel** [comment] 2016-12-14 14:26
The version numbers affects other builds as well. I opened #1065 to track that.

Do you have an optionally local build (https://tabrisjs.com/documentation/latest/local-build)?

**Comment by bFlood** [comment] 2016-12-14 14:27
I looked at the summary build logs from a build 8 days ago (working) and one made yesterday (not working). The logs look pretty different, I can only assume something has changed on on your build servers.

New Log from 12/14
``` log
Starting build
Preparing build environment
Using build template revision 10680ba7798d6f2dd11d689e807759398b87422b
Build environment created 58260286634fb0e4a4c0bf6d
Cloning app from https://github.com/spatialdatalogic/sdlmobile3.git
Building from branch master
Using app revision 808f887a3a3cfe9053e8c93697fdda0fa3e1dc6f
Processing App Directory
Applying Cordova project structure
Applying config.xml
Writing iOS Certificate and profile 'sdlmobile3_2016'
Writing Android keystore 'sdlmobile3_release_android'
Encrypting iOS Certificate Password
Encrypting Android Passwords
These things will be built:
  App Id: com.sdlportal.sdlmobile3
  Tabris.js Version: 1.10.0
  Debug Mode: false
  Platform: ANDROID
Creating build job c7e0627da9d6bdeda0831264c3ce10245cb352a1
Scheduling job (58260286634fb0e4a4c0bf6d). This may take a few minutes...
Done. Build passed. You can download the apps now.
```

Old Log from 12/4
``` log
Starting build
Cloning build template
Using build template revision 2da0c9d32773d1518a12963167734b1ce9a8bf3e
Build environment created 584ff6317507b0e4786d2f1c
Cloning app from https://github.com/spatialdatalogic/sdlmobile3.git
Building from branch master
Using app revision 8924b5ce112a00aff8dc4d02c0e8317202d6e031
Processing App Directory
Applying Cordova project structure
Applying config.xml
Writing Android keystore 'sdlmobile3_release_android'
Encrypting Android Passwords
Encrypting Android Passwords
These things will be built:
  App Id: com.sdlportal.sdlmobile3
  Tabris.js Version: 1.10.0
  Bundle Developer App: false
  Enable Developer Console: false
  Platform: ANDROID
Creating build job f33dbd14d5dcd9d1e4a581f9e6ecd64fb79db776
Scheduling job (584ff6317507b0e4786d2f1c). This may take a few minutes...
Done. Build passed. You can download the apps now.
```

**Comment by mpost** [comment] 2016-12-14 14:32
We have just build production android and ios apps (with upload to testflight). The build successfully passed and the apps also ran on the devices as expected.

Could the problem be related to some cordova plugin?

**Comment by fwaibel** [comment] 2016-12-14 14:32
Among other things I can see is that your app revision changed between these two builds.
The working build is `808f887a3a3cfe9053e8c93697fdda0fa3e1dc6f` the broken build `8924b5ce112a00aff8dc4d02c0e8317202d6e031`. Could you create a branch pointing to your old revision and build this?

**Comment by bFlood** [comment] 2016-12-14 14:52
I will try that but I don't think that is the issue, the updates to the repo were minor and only in the js files. I'll also look at some of the plugins

**Comment by bFlood** [comment] 2016-12-14 17:59
I have removed all plugins from the app, it compiles but still gives the same error on Android

``` java
12-14 12:57:21.361     910-2214/? E/Parcel﹕ Class not found when unmarshalling: com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp
    java.lang.ClassNotFoundException: com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:309)
            at java.lang.Class.forName(Class.java:273)
            at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
            at android.os.Parcel.readParcelable(Parcel.java:2245)
            at android.os.Parcel.readValue(Parcel.java:2152)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.BaseBundle.getString(BaseBundle.java:918)
            at android.content.Intent.getStringExtra(Intent.java:5794)
            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2411)
            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1892)
            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5457)
            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5241)
            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:143)
            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3418)
            at android.os.Binder.execTransact(Binder.java:446)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:309)
            at java.lang.Class.forName(Class.java:273)
            at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
            at android.os.Parcel.readParcelable(Parcel.java:2245)
            at android.os.Parcel.readValue(Parcel.java:2152)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.BaseBundle.getString(BaseBundle.java:918)
            at android.content.Intent.getStringExtra(Intent.java:5794)
            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2411)
            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1892)
            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5457)
            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5241)
            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:143)
            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3418)
            at android.os.Binder.execTransact(Binder.java:446)
    Suppressed: java.lang.ClassNotFoundException: com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by irbull** [comment] 2016-12-14 23:18
@bFlood I have analyzed your dex file and the missing class is indeed in the APK. This means that the build service is likely pulling together all the pieces. This may be configuration problem in the manifest related to the search path for the classes. Has anyone from EclipseSource double checked your project layout? We have refactored the build service lately, and maybe a once support cordova project layout no longer works?

**Comment by fwaibel** [comment] 2016-12-15 10:51
Seems we are kind of stuck here. May I ask you for permission to download your apk for local investigation?

**Comment by bFlood** [comment] 2016-12-15 11:50
Yes, no problem. I'll be in the office soon to comment more as well. Thank you

**Comment by fwaibel** [comment] 2016-12-15 12:51
Unfortunately you interchanged the logs. So on first sight everything looked good. When crosschecking the `woking` app I got a plain *white screen* - no exception so far.
```

**Comment by bFlood** [comment] 2016-12-15 13:01
@fwaibel what do you mean I interchanged the logs? the plain white screen is exactly what happens on the latest builds

@irbull I think this may be the issue, I recall having to change to an older cordova project layout to get some portion of a custom tabris plugin to compile (I believe it was something on the iOS side, the tabris maps plugin might be a place to look, I think it needed a www folder). that said, I've slowly been build up a brand new app and adding portions of the other app to it. I'll let you know what I find

**Comment by fwaibel** [comment] 2016-12-15 13:08
@bFlood The logs titled `New Log from 12/14` is from the working app.

We'll have a closer look at the _white screen_. Could you meanwhile run a test build from the branch created as mentioned in the comment before? Maybe we get some insights from that build.

**Comment by fwaibel** [comment] 2016-12-15 13:53
@bFlood Nothing suspicious in the logs of the _white app_. Especially no exceptions.

Did you find some time and were able to trigger a _test_ build from the branch as mentioned in the my comment (https://github.com/eclipsesource/tabris-js/issues/1056#issuecomment-267320140) above?

**Comment by bFlood** [comment] 2016-12-15 16:48
sorry, I had to work on something else for a bit

1. I was able to reproduce the blank white screen with no android exception on another, yet untested device. So I don't know what to make of that. just to reiterate, this same app works fine from a Debug build so its not the app logic itself causing the problem

2. I'm having problems building now, I've never seen this error before. are you guys maybe updating the servers?

``` log
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-23' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 20.526 secs
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-23' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Please install Android target: "android-23".
Hint: Open the SDK manager by running: /usr/local/android-sdk-24.0.2/tools/android
You will require:
1. "SDK Platform" for android-23
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)
Warning: Command failed: cordova build --device --release
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-23' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-23' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Please install Android target: "android-23".
Hint: Open the SDK manager by running: /usr/local/android-sdk-24.0.2/tools/android
You will require:
1. "SDK Platform" for android-23
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)
 Use --force to continue.
Aborted due to warnings.
travis_time:end:1ce2c5c2:start=1481819765393705906,finish=1481819820672943209,duration=55279237303

The command "grunt build deploy" exited with 6.
```

**Comment by fwaibel** [comment] 2016-12-15 20:16
@bFlood Yes we continuously work on the server side. One of todays changes supposed to go into the 2.x development sneaked into 1.10 and caused the Android build problems. Sorry for the additional inconvenience caused.

This has be reverted and you should be able to do the build from the test branch now.

Regarding the _white page_ problem the only difference I am aware of between debug and production builds is the additional cordova parameter `--release`. We never encountered a situation like yours before.

**Comment by fwaibel** [comment] 2016-12-16 13:55
@bFlood The snapshot environment https://snapshot.tabrisjs.com/ is prepared and you should be able to access your build jobs there.

**Comment by bFlood** [comment] 2016-12-16 14:48
thank you @fwaibel , I really appreciate the effort

the first build using the snapshot server caused the same issue (white screen, class loader exception on some devices, not on others), so I believe you are correct in saying this is not a build server issue. Can you just confirm the exact date of the snapshot?

I'm going to try building with older versions, with and without plugins and also by building up a brand new app again. I'll let you know what I find today. Is it possible to leave this snapshot server running for a couple of days?

thanks again

**Comment by fwaibel** [comment] 2016-12-16 15:09
@bFlood The code powering the server-side part is from early November (9th of November). The build template is from end of November (25th of November).

To validate the snapshot environment it might still be valuable to try to reproduce the latest known working build. If you create a `test` branch in your repository

```
$ git branch test 808f887a3a3cfe9053e8c93697fdda0fa3e1dc6f
```

and configure this branch in the build settings.

**Comment by bFlood** [comment] 2016-12-16 15:33
yes, I agree. I'll let you know how it goes. It will have to change a little since there were updates to plugins during that timeframe, I'm not sure I can get it exactly back to where it was for all plugins. that said, I removed all the plugins and tested and I still got the error, so I don't think its them either

quick question:
1. the debug build works, when I connect via url/http-server, the exact same app that is failing in release works as expected. Can you think of anything that would cause this to happen? Any issue within the app code itself has always failed similarly between debug and release before

thanks

**Comment by fwaibel** [comment] 2016-12-16 16:37
@bFlood I scanned the log files from your current builds and found a discrepancy between the `TABRIS_JS_VERSION` (usually configured in the build job)
```
$ export TABRIS_JS_VERSION="1.9.0"
$ export TABRIS_BUILD_ID="585413772914b0e41748350f"
```
and the Tabris version used in the app:
```
└── tabris@1.10.0 
```
If I remember correctly the tabris code is bundled inside the debug app. So you might use 1.9 in debug builds and 1.10 in your release builds.
Could you check your settings in the build job? Maybe the version bump to 1.10 didn't find it's way to the job configuration...

**Comment by bFlood** [comment] 2016-12-16 17:33
@fwaibel - thanks, I was just playing with those settings, the original test used 1.10.0

**Comment by bFlood** [comment] 2016-12-16 19:09
@fwaibel finally figured this out and yes, it was my fault. you can close this ticket and thanks again for all the effort trying to resolve this

for anyone else that has problems with a release build that does not affect the debug build:
1. enable the developer console, logs that show up here do not necessarily make it into the native platform logs. I did not realize you could have a release build with this option, this would have been solved a lot earlier had I done this originally. 

2. the real problem was a require statement with a path that had proper spelling but incorrect case. these files are imported in the debug build (I'm guessing because of the way http-server works) but will not work in release builds. an error shows up in the tabris dev console but it does not show up in the native logs. 

so, one single "P" instead of "p" caused my issue. oh well, thanks again

**Comment by fwaibel** [comment] 2016-12-16 20:39
@bFlood Thanks for keeping us in the loop. I'm glad we finally figured out what the problem was.

I'll close this issue and shut down the snapshot environment on Monday.

**Closed by fwaibel** 2016-12-16 20:39 UTC
