### ISSUE TITLE
iOS ScrollView Overscroll Discrepancy 

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1182] opened 2017-03-09 22:34 UTC
I am seeing a strange behavior on iOS tabris 1.10 where when I pull down and receive that overscroll effect, when it finally stabilizes visually on the screen the on('scroll') continues to fire constantly at between -.3 and -6, never stabilizing. You can also see in the UI in certain cases the scroll view is now off by basically 1 pixel.  I am on IPhone 6s with latest updates. Let me know if you are having any issues reproducing.

**Comment by mpost** [comment] 2017-06-14 10:21
We have verified with the _collectionview-scroll.js_ snippet on Tabris.js 2.x and could not reproduce the problem. I am therefore closing this issue. Please reopen of you have any more problems.

**Closed by mpost** 2017-06-14 10:21 UTC
Labels: bug, ios
