### ISSUE TITLE
Negative layout dimensions handling is incosistent 

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1480] opened 2017-08-22 12:18 UTC
Giving e.g. a TextView a negative height makes it behave as if it was 0 on windows, but makes the element as big as it's parent on Android. Did not test it on iOS. 

We need to agree on how it should behave and implement that in JavaScript so the platforms don't have to deal with it.

**Comment by mpost** [comment] 2017-08-22 14:11
Relates to https://github.com/eclipsesource/tabris-js/issues/1406

**Comment by mpost** [comment] 2018-06-14 09:56
Closing as duplicate of #1406.

**Closed by mpost** 2018-06-14 09:56 UTC
Labels: api, bug, js
