### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1238] opened 2017-04-13 07:04 UTC
hello is it possible to have  a border on the widget(border-top,border-bottom,border-left,border-right)?

**Comment by cookieguru** [comment] 2017-04-13 07:16
Duplicate of #1016

**Comment by ishigo1987** [comment] 2017-04-13 07:19
ok it's not really obvious right now

**Comment by ralfstx** [comment] 2017-04-13 12:47
Closing as dup of #1016. Thanks, @cookieguru.

@ishigo1987 It's not yet possible. The request is tracked by issue #1016. BTW, you might want to join our [slack channel](https://tabrisjs.herokuapp.com/) to ask further questions.

**Closed by ralfstx** 2017-04-13 12:47 UTC
