### ISSUE TITLE
Image load event not firing when cache is warm

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#867] opened 2016-05-27 23:34 UTC
It seems when the image exists in cache, meaning an image view has already loaded it at some point prior in the app, the load event does not fire on subsequent ImageViews.

**Comment by mpost** [comment] 2016-05-30 07:35
@dested What platform are you seeing this behavior on?

**Comment by dested** [comment] 2016-05-30 08:27
Android  
#849  It seems to be this issue.

**Comment by mpost** [comment] 2016-11-15 13:36
The issue is indeed the same as described in #849.

The problem is that when the image comes from the cache it is applied instantly when the `ImageView` is created. The listener to notify of the `load` event is not registered at this point.

We will make an Android client side adjustment to make sure that the image is only set after the initial listener is registered.

**Comment by mpost** [comment] 2016-11-15 15:03
Fixed in the 2.0 stream.

**Closed by mpost** 2016-11-15 15:03 UTC
