### ISSUE TITLE
ImageView cannot load big size images

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1522] opened 2017-10-13 17:44 UTC
### Problem description

In our private project, we have a lock screen and we use a background image for it. We have registered `app#background` event handler that opens the lock screen. When the `background` event is triggered (the iOS device auto locks), the lock screen is opened. However, in this case, the background image sometimes does not appear when we reopen the app.

The issue can be reproduced with the represented simple snippet below. To let you know that we can reproduce it more easily with the big size images.

### Expected behavior

The background image must appear regardless of the size of the image. 

### Environment

- Tabris.js version: 2.5
- Device: iPhone 6
- OS: 11.3.1

### Code snippet

```javascript
const {ImageView, ui, app} = require('tabris');

function createImageView() {
  new ImageView({
    left: 10, top: 10, right: 10, bottom: 10,
    image: 'http://www.pngpix.com/wp-content/uploads/2016/06/PNGPIX-COM-Silver-Audi-Car-PNG-Image.png',
    background: 'red',
    scaleMode: 'fill'
  }).appendTo(ui.contentView);
}

app.on('background', () => createImageView());
```
To detect the issue, we have to wait a while for the device to be locked.

**Comment by bev-on** [comment] 2017-10-16 12:19
I wasn't able to replicate this issue on iPhone 6, v10.3.2 and neither on Android.

Image is appearing after locking and unlocking device. Maybe this issue is related to iOS 11 specifically?

**Comment by elshadsm** [comment] 2017-10-16 19:43
@bev-on `To be able to detect the issue we must wait for a while when the device is locked.` and it happens only in iOS : )

**Comment by bev-on** [comment] 2017-10-18 13:37
@elshadsm Oh, this is not TabrisJS bug, this is because of iOS restrictions of background processes.

https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

Most of apps are getting killed after few seconds in background, there is no true multitasking on iOS and this is how iOS always feels much faster than Android even if Android device has better hardware. They simply not allow apps to run in background, unless very rear specific cases.

In general, it's not good idea to rely on background app execution even on Android since some battery saver features on Android limits background apps as well. You can't trust OS or user that your app will stay in background forever.

Solution is that after executing background task, you can save app state using ```localStorage``` and when you detect that app is opened by user, check last app state and open same page or image again if you detect that app was killed in background.  If it's not clear how to do this, let me know and I can write small snippet using localStorage to show how to reload image if app was killed be iOS.

**Comment by karolszafranski** [comment] 2018-05-30 14:56
@elshadsm would following workflow fit your use case?

1. User launch the app
2. You download the big image when the application is launched, and store it for using later. We know that eventually, the app will go to the background at some time, so the image will be required anyway.

    The only problem which might occur here is if the image is dynamic, and you should use a different one depending on actions user performed, or the time.

3. When a user closes the app, and it is moved to the background state you create the `ImageView` with URL pointing to the local copy.

We cannot help in any other way, while the app is stopped by the OS. Let's assume for a moment that this is not the case. How your app will behave if there will be no network connection or if the server will be not available at the time when user close it? In my opinion iOS killing/freezing, the unused app fits the same category of issues.

**Comment by elshadsm** [comment] 2018-05-30 15:07
Thanks Karol, to let you that we use the image from the local. I think I could fix the issue by setting the image again when the page appears or another easy solution.

**Comment by mpost** [comment] 2018-06-14 09:40
Closing as "works as intended". Please reopen if you have any more issues.

**Closed by mpost** 2018-06-14 09:40 UTC
Labels: bug, ios
